name:                objc-contacts
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Contacts framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Contacts.CNChangeHistoryAddContactEvent
  - ObjC.Contacts.CNChangeHistoryAddGroupEvent
  - ObjC.Contacts.CNChangeHistoryAddMemberToGroupEvent
  - ObjC.Contacts.CNChangeHistoryAddSubgroupToGroupEvent
  - ObjC.Contacts.CNChangeHistoryDeleteContactEvent
  - ObjC.Contacts.CNChangeHistoryDeleteGroupEvent
  - ObjC.Contacts.CNChangeHistoryDropEverythingEvent
  - ObjC.Contacts.CNChangeHistoryEvent
  - ObjC.Contacts.CNChangeHistoryFetchRequest
  - ObjC.Contacts.CNChangeHistoryRemoveMemberFromGroupEvent
  - ObjC.Contacts.CNChangeHistoryRemoveSubgroupFromGroupEvent
  - ObjC.Contacts.CNChangeHistoryUpdateContactEvent
  - ObjC.Contacts.CNChangeHistoryUpdateGroupEvent
  - ObjC.Contacts.CNContact
  - ObjC.Contacts.CNContactFetchRequest
  - ObjC.Contacts.CNContactFormatter
  - ObjC.Contacts.CNContactProperty
  - ObjC.Contacts.CNContactRelation
  - ObjC.Contacts.CNContactStore
  - ObjC.Contacts.CNContactVCardSerialization
  - ObjC.Contacts.CNContactsUserDefaults
  - ObjC.Contacts.CNContainer
  - ObjC.Contacts.CNFetchRequest
  - ObjC.Contacts.CNFetchResult
  - ObjC.Contacts.CNGroup
  - ObjC.Contacts.CNInstantMessageAddress
  - ObjC.Contacts.CNLabeledValue
  - ObjC.Contacts.CNMutableContact
  - ObjC.Contacts.CNMutableGroup
  - ObjC.Contacts.CNMutablePostalAddress
  - ObjC.Contacts.CNPhoneNumber
  - ObjC.Contacts.CNPostalAddress
  - ObjC.Contacts.CNPostalAddressFormatter
  - ObjC.Contacts.CNSaveRequest
  - ObjC.Contacts.CNSocialProfile
  - ObjC.Contacts.Enums
  - ObjC.Contacts.Internal.Classes
  - ObjC.Contacts.Internal.Enums
