name:                apple-coreimage-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CoreImage framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen
- apple-iosurface-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CoreImage.CIAztecCodeDescriptor
  - ObjC.CoreImage.CIBarcodeDescriptor
  - ObjC.CoreImage.CIBlendKernel
  - ObjC.CoreImage.CIColor
  - ObjC.CoreImage.CIColorKernel
  - ObjC.CoreImage.CIContext
  - ObjC.CoreImage.CIDataMatrixCodeDescriptor
  - ObjC.CoreImage.CIDetector
  - ObjC.CoreImage.CIFaceFeature
  - ObjC.CoreImage.CIFeature
  - ObjC.CoreImage.CIFilter
  - ObjC.CoreImage.CIFilterGenerator
  - ObjC.CoreImage.CIFilterShape
  - ObjC.CoreImage.CIImage
  - ObjC.CoreImage.CIImageAccumulator
  - ObjC.CoreImage.CIImageProcessorKernel
  - ObjC.CoreImage.CIKernel
  - ObjC.CoreImage.CIPDF417CodeDescriptor
  - ObjC.CoreImage.CIPlugIn
  - ObjC.CoreImage.CIQRCodeDescriptor
  - ObjC.CoreImage.CIQRCodeFeature
  - ObjC.CoreImage.CIRAWFilter
  - ObjC.CoreImage.CIRectangleFeature
  - ObjC.CoreImage.CIRenderDestination
  - ObjC.CoreImage.CIRenderInfo
  - ObjC.CoreImage.CIRenderTask
  - ObjC.CoreImage.CISampler
  - ObjC.CoreImage.CITextFeature
  - ObjC.CoreImage.CIVector
  - ObjC.CoreImage.CIWarpKernel
  - ObjC.CoreImage.Delegate.CIFilter
  - ObjC.CoreImage.Delegate.CIFilterConstructor
  - ObjC.CoreImage.Delegate.CIImageProcessorInput
  - ObjC.CoreImage.Delegate.CIImageProcessorOutput
  - ObjC.CoreImage.Enums
  - ObjC.CoreImage.Internal.Classes
  - ObjC.CoreImage.Internal.Enums
