name:                objc-exceptionhandling
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ExceptionHandling framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ExceptionHandling.Internal.Classes
  - ObjC.ExceptionHandling.NSExceptionHandler
  - ObjC.ExceptionHandling.NSObject
