name:                apple-avkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AVKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-avfoundation-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AVKit.AVCaptureView
  - ObjC.AVKit.AVPictureInPictureController
  - ObjC.AVKit.AVPictureInPictureControllerContentSource
  - ObjC.AVKit.AVPlaybackSpeed
  - ObjC.AVKit.AVPlayerView
  - ObjC.AVKit.AVRoutePickerView
  - ObjC.AVKit.Delegate.AVCaptureViewDelegate
  - ObjC.AVKit.Delegate.AVPictureInPictureControllerDelegate
  - ObjC.AVKit.Delegate.AVPictureInPictureSampleBufferPlaybackDelegate
  - ObjC.AVKit.Delegate.AVPlayerViewDelegate
  - ObjC.AVKit.Delegate.AVPlayerViewPictureInPictureDelegate
  - ObjC.AVKit.Delegate.AVRoutePickerViewDelegate
  - ObjC.AVKit.Enums
  - ObjC.AVKit.Internal.Classes
  - ObjC.AVKit.Internal.Enums
