name:                apple-scenekit-quartzcore-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SceneKit extensions on QuartzCore framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-quartzcore-gen
- apple-scenekit-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SceneKit.CAAnimation
