name:                apple-javaruntimesupport-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the JavaRuntimeSupport framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.JavaRuntimeSupport.Delegate.JRSMenuDelegate
  - ObjC.JavaRuntimeSupport.Delegate.JRSRemoteLayer
  - ObjC.JavaRuntimeSupport.Internal.Classes
  - ObjC.JavaRuntimeSupport.JRSAppKitAWT
  - ObjC.JavaRuntimeSupport.JRSDrag
  - ObjC.JavaRuntimeSupport.JRSInputMethodController
  - ObjC.JavaRuntimeSupport.JRSRenderServer
  - ObjC.JavaRuntimeSupport.JRSSymbolicator
