name:                objc-mapkit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the MapKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-contacts
- objc-corelocation
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.MapKit.Enums
  - ObjC.MapKit.Internal.Classes
  - ObjC.MapKit.Internal.Enums
  - ObjC.MapKit.MKAddress
  - ObjC.MapKit.MKAddressFilter
  - ObjC.MapKit.MKAddressRepresentations
  - ObjC.MapKit.MKAnnotationView
  - ObjC.MapKit.MKCircle
  - ObjC.MapKit.MKCircleRenderer
  - ObjC.MapKit.MKClusterAnnotation
  - ObjC.MapKit.MKCompassButton
  - ObjC.MapKit.MKDirections
  - ObjC.MapKit.MKDirectionsRequest
  - ObjC.MapKit.MKDirectionsResponse
  - ObjC.MapKit.MKDistanceFormatter
  - ObjC.MapKit.MKETAResponse
  - ObjC.MapKit.MKGeoJSONDecoder
  - ObjC.MapKit.MKGeoJSONFeature
  - ObjC.MapKit.MKGeocodingRequest
  - ObjC.MapKit.MKGeodesicPolyline
  - ObjC.MapKit.MKGradientPolylineRenderer
  - ObjC.MapKit.MKHybridMapConfiguration
  - ObjC.MapKit.MKImageryMapConfiguration
  - ObjC.MapKit.MKLocalPointsOfInterestRequest
  - ObjC.MapKit.MKLocalSearch
  - ObjC.MapKit.MKLocalSearchCompleter
  - ObjC.MapKit.MKLocalSearchCompletion
  - ObjC.MapKit.MKLocalSearchRequest
  - ObjC.MapKit.MKLocalSearchResponse
  - ObjC.MapKit.MKLookAroundScene
  - ObjC.MapKit.MKLookAroundSceneRequest
  - ObjC.MapKit.MKLookAroundSnapshot
  - ObjC.MapKit.MKLookAroundSnapshotOptions
  - ObjC.MapKit.MKLookAroundSnapshotter
  - ObjC.MapKit.MKLookAroundViewController
  - ObjC.MapKit.MKMapCamera
  - ObjC.MapKit.MKMapCameraBoundary
  - ObjC.MapKit.MKMapCameraZoomRange
  - ObjC.MapKit.MKMapConfiguration
  - ObjC.MapKit.MKMapItem
  - ObjC.MapKit.MKMapItemAnnotation
  - ObjC.MapKit.MKMapItemDetailSelectionAccessoryPresentationStyle
  - ObjC.MapKit.MKMapItemDetailViewController
  - ObjC.MapKit.MKMapItemIdentifier
  - ObjC.MapKit.MKMapItemRequest
  - ObjC.MapKit.MKMapSnapshot
  - ObjC.MapKit.MKMapSnapshotOptions
  - ObjC.MapKit.MKMapSnapshotter
  - ObjC.MapKit.MKMapView
  - ObjC.MapKit.MKMarkerAnnotationView
  - ObjC.MapKit.MKMultiPoint
  - ObjC.MapKit.MKMultiPolygon
  - ObjC.MapKit.MKMultiPolygonRenderer
  - ObjC.MapKit.MKMultiPolyline
  - ObjC.MapKit.MKMultiPolylineRenderer
  - ObjC.MapKit.MKOverlayPathRenderer
  - ObjC.MapKit.MKOverlayRenderer
  - ObjC.MapKit.MKPinAnnotationView
  - ObjC.MapKit.MKPitchControl
  - ObjC.MapKit.MKPlacemark
  - ObjC.MapKit.MKPointAnnotation
  - ObjC.MapKit.MKPointOfInterestFilter
  - ObjC.MapKit.MKPolygon
  - ObjC.MapKit.MKPolygonRenderer
  - ObjC.MapKit.MKPolyline
  - ObjC.MapKit.MKPolylineRenderer
  - ObjC.MapKit.MKReverseGeocodingRequest
  - ObjC.MapKit.MKRoute
  - ObjC.MapKit.MKRouteStep
  - ObjC.MapKit.MKSelectionAccessory
  - ObjC.MapKit.MKShape
  - ObjC.MapKit.MKStandardMapConfiguration
  - ObjC.MapKit.MKTileOverlay
  - ObjC.MapKit.MKTileOverlayRenderer
  - ObjC.MapKit.MKUserLocation
  - ObjC.MapKit.MKUserLocationView
  - ObjC.MapKit.MKZoomControl
  - ObjC.MapKit.NSUserActivity
  - ObjC.MapKit.NSValue
