name:                objc-social
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Social framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Social.Enums
  - ObjC.Social.Internal.Classes
  - ObjC.Social.Internal.Enums
  - ObjC.Social.SLComposeServiceViewController
  - ObjC.Social.SLRequest
