name:                objc-mediaaccessibility
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the MediaAccessibility framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.MediaAccessibility.Enums
  - ObjC.MediaAccessibility.Internal.Classes
  - ObjC.MediaAccessibility.Internal.Enums
  - ObjC.MediaAccessibility.MAFlashingLightsProcessor
  - ObjC.MediaAccessibility.MAFlashingLightsProcessorResult
  - ObjC.MediaAccessibility.MAMusicHapticsManager
