name:                objc-medialibrary
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the MediaLibrary framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.MediaLibrary.Enums
  - ObjC.MediaLibrary.Internal.Classes
  - ObjC.MediaLibrary.Internal.Enums
  - ObjC.MediaLibrary.MLMediaGroup
  - ObjC.MediaLibrary.MLMediaLibrary
  - ObjC.MediaLibrary.MLMediaObject
  - ObjC.MediaLibrary.MLMediaSource
