name:                apple-healthkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the HealthKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen
- apple-uniformtypeidentifiers-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.HealthKit.Delegate.HKLiveWorkoutBuilderDelegate
  - ObjC.HealthKit.Delegate.HKWorkoutSessionDelegate
  - ObjC.HealthKit.Enums
  - ObjC.HealthKit.HKActivityMoveModeObject
  - ObjC.HealthKit.HKActivitySummary
  - ObjC.HealthKit.HKActivitySummaryQuery
  - ObjC.HealthKit.HKActivitySummaryType
  - ObjC.HealthKit.HKAnchoredObjectQuery
  - ObjC.HealthKit.HKAttachment
  - ObjC.HealthKit.HKAttachmentStore
  - ObjC.HealthKit.HKAudiogramSample
  - ObjC.HealthKit.HKAudiogramSampleType
  - ObjC.HealthKit.HKAudiogramSensitivityPoint
  - ObjC.HealthKit.HKAudiogramSensitivityPointClampingRange
  - ObjC.HealthKit.HKAudiogramSensitivityTest
  - ObjC.HealthKit.HKBiologicalSexObject
  - ObjC.HealthKit.HKBloodTypeObject
  - ObjC.HealthKit.HKCDADocument
  - ObjC.HealthKit.HKCDADocumentSample
  - ObjC.HealthKit.HKCategorySample
  - ObjC.HealthKit.HKCategoryType
  - ObjC.HealthKit.HKCharacteristicType
  - ObjC.HealthKit.HKClinicalCoding
  - ObjC.HealthKit.HKClinicalRecord
  - ObjC.HealthKit.HKClinicalType
  - ObjC.HealthKit.HKContactsLensSpecification
  - ObjC.HealthKit.HKContactsPrescription
  - ObjC.HealthKit.HKCorrelation
  - ObjC.HealthKit.HKCorrelationQuery
  - ObjC.HealthKit.HKCorrelationType
  - ObjC.HealthKit.HKCumulativeQuantitySample
  - ObjC.HealthKit.HKCumulativeQuantitySeriesSample
  - ObjC.HealthKit.HKDeletedObject
  - ObjC.HealthKit.HKDevice
  - ObjC.HealthKit.HKDiscreteQuantitySample
  - ObjC.HealthKit.HKDocumentQuery
  - ObjC.HealthKit.HKDocumentSample
  - ObjC.HealthKit.HKDocumentType
  - ObjC.HealthKit.HKElectrocardiogram
  - ObjC.HealthKit.HKElectrocardiogramQuery
  - ObjC.HealthKit.HKElectrocardiogramType
  - ObjC.HealthKit.HKElectrocardiogramVoltageMeasurement
  - ObjC.HealthKit.HKFHIRResource
  - ObjC.HealthKit.HKFHIRVersion
  - ObjC.HealthKit.HKFitzpatrickSkinTypeObject
  - ObjC.HealthKit.HKGAD7Assessment
  - ObjC.HealthKit.HKGlassesLensSpecification
  - ObjC.HealthKit.HKGlassesPrescription
  - ObjC.HealthKit.HKHealthConceptIdentifier
  - ObjC.HealthKit.HKHealthStore
  - ObjC.HealthKit.HKHeartbeatSeriesBuilder
  - ObjC.HealthKit.HKHeartbeatSeriesQuery
  - ObjC.HealthKit.HKHeartbeatSeriesSample
  - ObjC.HealthKit.HKLensSpecification
  - ObjC.HealthKit.HKLiveWorkoutBuilder
  - ObjC.HealthKit.HKLiveWorkoutDataSource
  - ObjC.HealthKit.HKMedicationConcept
  - ObjC.HealthKit.HKMedicationDoseEvent
  - ObjC.HealthKit.HKMedicationDoseEventType
  - ObjC.HealthKit.HKObject
  - ObjC.HealthKit.HKObjectType
  - ObjC.HealthKit.HKObserverQuery
  - ObjC.HealthKit.HKPHQ9Assessment
  - ObjC.HealthKit.HKPrescriptionType
  - ObjC.HealthKit.HKQuantity
  - ObjC.HealthKit.HKQuantitySample
  - ObjC.HealthKit.HKQuantitySeriesSampleBuilder
  - ObjC.HealthKit.HKQuantitySeriesSampleQuery
  - ObjC.HealthKit.HKQuantityType
  - ObjC.HealthKit.HKQuery
  - ObjC.HealthKit.HKQueryAnchor
  - ObjC.HealthKit.HKQueryDescriptor
  - ObjC.HealthKit.HKSample
  - ObjC.HealthKit.HKSampleQuery
  - ObjC.HealthKit.HKSampleType
  - ObjC.HealthKit.HKScoredAssessment
  - ObjC.HealthKit.HKScoredAssessmentType
  - ObjC.HealthKit.HKSeriesBuilder
  - ObjC.HealthKit.HKSeriesSample
  - ObjC.HealthKit.HKSeriesType
  - ObjC.HealthKit.HKSource
  - ObjC.HealthKit.HKSourceQuery
  - ObjC.HealthKit.HKSourceRevision
  - ObjC.HealthKit.HKStateOfMind
  - ObjC.HealthKit.HKStateOfMindType
  - ObjC.HealthKit.HKStatistics
  - ObjC.HealthKit.HKStatisticsCollection
  - ObjC.HealthKit.HKStatisticsCollectionQuery
  - ObjC.HealthKit.HKStatisticsQuery
  - ObjC.HealthKit.HKUnit
  - ObjC.HealthKit.HKUserAnnotatedMedication
  - ObjC.HealthKit.HKUserAnnotatedMedicationQuery
  - ObjC.HealthKit.HKUserAnnotatedMedicationType
  - ObjC.HealthKit.HKVerifiableClinicalRecord
  - ObjC.HealthKit.HKVerifiableClinicalRecordQuery
  - ObjC.HealthKit.HKVerifiableClinicalRecordSubject
  - ObjC.HealthKit.HKVisionPrescription
  - ObjC.HealthKit.HKVisionPrism
  - ObjC.HealthKit.HKWheelchairUseObject
  - ObjC.HealthKit.HKWorkout
  - ObjC.HealthKit.HKWorkoutActivity
  - ObjC.HealthKit.HKWorkoutBuilder
  - ObjC.HealthKit.HKWorkoutConfiguration
  - ObjC.HealthKit.HKWorkoutEffortRelationship
  - ObjC.HealthKit.HKWorkoutEffortRelationshipQuery
  - ObjC.HealthKit.HKWorkoutEvent
  - ObjC.HealthKit.HKWorkoutRoute
  - ObjC.HealthKit.HKWorkoutRouteBuilder
  - ObjC.HealthKit.HKWorkoutRouteQuery
  - ObjC.HealthKit.HKWorkoutSession
  - ObjC.HealthKit.HKWorkoutType
  - ObjC.HealthKit.Internal.Classes
  - ObjC.HealthKit.Internal.Enums
