name:                apple-paravirtualizedgraphics-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ParavirtualizedGraphics framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ParavirtualizedGraphics.Delegate.PGDevice
  - ObjC.ParavirtualizedGraphics.Delegate.PGDisplay
  - ObjC.ParavirtualizedGraphics.Enums
  - ObjC.ParavirtualizedGraphics.Internal.Classes
  - ObjC.ParavirtualizedGraphics.Internal.Enums
  - ObjC.ParavirtualizedGraphics.Internal.Structs
  - ObjC.ParavirtualizedGraphics.PGDeviceDescriptor
  - ObjC.ParavirtualizedGraphics.PGDisplayDescriptor
  - ObjC.ParavirtualizedGraphics.PGDisplayMode
  - ObjC.ParavirtualizedGraphics.Structs
