name:                objc-discrecording
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the DiscRecording framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.DiscRecording.DRBurn
  - ObjC.DiscRecording.DRCDTextBlock
  - ObjC.DiscRecording.DRDevice
  - ObjC.DiscRecording.DRErase
  - ObjC.DiscRecording.DRFSObject
  - ObjC.DiscRecording.DRFile
  - ObjC.DiscRecording.DRFolder
  - ObjC.DiscRecording.DRMSF
  - ObjC.DiscRecording.DRMSFFormatter
  - ObjC.DiscRecording.DRNotificationCenter
  - ObjC.DiscRecording.DRTrack
  - ObjC.DiscRecording.Internal.Classes
  - ObjC.DiscRecording.Internal.Structs
  - ObjC.DiscRecording.Structs
