name:                objc-adservices
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AdServices framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AdServices.AAAttribution
  - ObjC.AdServices.Enums
  - ObjC.AdServices.Internal.Classes
  - ObjC.AdServices.Internal.Enums
