name:                objc-screensaver
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ScreenSaver framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ScreenSaver.Internal.Classes
  - ObjC.ScreenSaver.ScreenSaverDefaults
  - ObjC.ScreenSaver.ScreenSaverView
