name:                apple-sensorkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SensorKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SensorKit.Delegate.SRSensorReaderDelegate
  - ObjC.SensorKit.Enums
  - ObjC.SensorKit.Internal.Classes
  - ObjC.SensorKit.Internal.Enums
  - ObjC.SensorKit.SRAcousticSettings
  - ObjC.SensorKit.SRAcousticSettingsAccessibility
  - ObjC.SensorKit.SRAcousticSettingsAccessibilityBackgroundSounds
  - ObjC.SensorKit.SRAcousticSettingsAccessibilityHeadphoneAccommodations
  - ObjC.SensorKit.SRAcousticSettingsMusicEQ
  - ObjC.SensorKit.SRAmbientLightSample
  - ObjC.SensorKit.SRApplicationUsage
  - ObjC.SensorKit.SRAudioLevel
  - ObjC.SensorKit.SRDeletionRecord
  - ObjC.SensorKit.SRDevice
  - ObjC.SensorKit.SRDeviceUsageReport
  - ObjC.SensorKit.SRElectrocardiogramData
  - ObjC.SensorKit.SRElectrocardiogramSample
  - ObjC.SensorKit.SRElectrocardiogramSession
  - ObjC.SensorKit.SRFaceMetrics
  - ObjC.SensorKit.SRFaceMetricsExpression
  - ObjC.SensorKit.SRFetchRequest
  - ObjC.SensorKit.SRFetchResult
  - ObjC.SensorKit.SRKeyboardMetrics
  - ObjC.SensorKit.SRKeyboardProbabilityMetric
  - ObjC.SensorKit.SRMediaEvent
  - ObjC.SensorKit.SRMessagesUsageReport
  - ObjC.SensorKit.SRNotificationUsage
  - ObjC.SensorKit.SRPhoneUsageReport
  - ObjC.SensorKit.SRPhotoplethysmogramAccelerometerSample
  - ObjC.SensorKit.SRPhotoplethysmogramOpticalSample
  - ObjC.SensorKit.SRPhotoplethysmogramSample
  - ObjC.SensorKit.SRSensorReader
  - ObjC.SensorKit.SRSleepSession
  - ObjC.SensorKit.SRSpeechExpression
  - ObjC.SensorKit.SRSpeechMetrics
  - ObjC.SensorKit.SRSupplementalCategory
  - ObjC.SensorKit.SRTextInputSession
  - ObjC.SensorKit.SRVisit
  - ObjC.SensorKit.SRWebUsage
  - ObjC.SensorKit.SRWristDetection
  - ObjC.SensorKit.SRWristTemperature
  - ObjC.SensorKit.SRWristTemperatureSession
