name:                apple-modelio-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ModelIO framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ModelIO.Delegate.MDLAssetResolver
  - ObjC.ModelIO.Delegate.MDLLightProbeIrradianceDataSource
  - ObjC.ModelIO.Delegate.MDLMeshBuffer
  - ObjC.ModelIO.Delegate.MDLMeshBufferAllocator
  - ObjC.ModelIO.Delegate.MDLMeshBufferZone
  - ObjC.ModelIO.Delegate.MDLNamed
  - ObjC.ModelIO.Delegate.MDLObjectContainerComponent
  - ObjC.ModelIO.Delegate.MDLTransformOp
  - ObjC.ModelIO.Enums
  - ObjC.ModelIO.Internal.Classes
  - ObjC.ModelIO.Internal.Enums
  - ObjC.ModelIO.MDLAnimatedMatrix4x4
  - ObjC.ModelIO.MDLAnimatedQuaternion
  - ObjC.ModelIO.MDLAnimatedQuaternionArray
  - ObjC.ModelIO.MDLAnimatedScalar
  - ObjC.ModelIO.MDLAnimatedScalarArray
  - ObjC.ModelIO.MDLAnimatedValue
  - ObjC.ModelIO.MDLAnimatedVector2
  - ObjC.ModelIO.MDLAnimatedVector3
  - ObjC.ModelIO.MDLAnimatedVector3Array
  - ObjC.ModelIO.MDLAnimatedVector4
  - ObjC.ModelIO.MDLAnimationBindComponent
  - ObjC.ModelIO.MDLAreaLight
  - ObjC.ModelIO.MDLAsset
  - ObjC.ModelIO.MDLBundleAssetResolver
  - ObjC.ModelIO.MDLCamera
  - ObjC.ModelIO.MDLCheckerboardTexture
  - ObjC.ModelIO.MDLColorSwatchTexture
  - ObjC.ModelIO.MDLLight
  - ObjC.ModelIO.MDLLightProbe
  - ObjC.ModelIO.MDLMaterial
  - ObjC.ModelIO.MDLMaterialProperty
  - ObjC.ModelIO.MDLMaterialPropertyConnection
  - ObjC.ModelIO.MDLMaterialPropertyGraph
  - ObjC.ModelIO.MDLMaterialPropertyNode
  - ObjC.ModelIO.MDLMatrix4x4Array
  - ObjC.ModelIO.MDLMesh
  - ObjC.ModelIO.MDLMeshBufferData
  - ObjC.ModelIO.MDLMeshBufferDataAllocator
  - ObjC.ModelIO.MDLMeshBufferMap
  - ObjC.ModelIO.MDLMeshBufferZoneDefault
  - ObjC.ModelIO.MDLNoiseTexture
  - ObjC.ModelIO.MDLNormalMapTexture
  - ObjC.ModelIO.MDLObject
  - ObjC.ModelIO.MDLObjectContainer
  - ObjC.ModelIO.MDLPackedJointAnimation
  - ObjC.ModelIO.MDLPathAssetResolver
  - ObjC.ModelIO.MDLPhotometricLight
  - ObjC.ModelIO.MDLPhysicallyPlausibleLight
  - ObjC.ModelIO.MDLPhysicallyPlausibleScatteringFunction
  - ObjC.ModelIO.MDLRelativeAssetResolver
  - ObjC.ModelIO.MDLScatteringFunction
  - ObjC.ModelIO.MDLSkeleton
  - ObjC.ModelIO.MDLSkyCubeTexture
  - ObjC.ModelIO.MDLStereoscopicCamera
  - ObjC.ModelIO.MDLSubmesh
  - ObjC.ModelIO.MDLSubmeshTopology
  - ObjC.ModelIO.MDLTexture
  - ObjC.ModelIO.MDLTextureFilter
  - ObjC.ModelIO.MDLTextureSampler
  - ObjC.ModelIO.MDLTransform
  - ObjC.ModelIO.MDLTransformMatrixOp
  - ObjC.ModelIO.MDLTransformOrientOp
  - ObjC.ModelIO.MDLTransformRotateOp
  - ObjC.ModelIO.MDLTransformRotateXOp
  - ObjC.ModelIO.MDLTransformRotateYOp
  - ObjC.ModelIO.MDLTransformRotateZOp
  - ObjC.ModelIO.MDLTransformScaleOp
  - ObjC.ModelIO.MDLTransformStack
  - ObjC.ModelIO.MDLTransformTranslateOp
  - ObjC.ModelIO.MDLURLTexture
  - ObjC.ModelIO.MDLUtility
  - ObjC.ModelIO.MDLVertexAttribute
  - ObjC.ModelIO.MDLVertexAttributeData
  - ObjC.ModelIO.MDLVertexBufferLayout
  - ObjC.ModelIO.MDLVertexDescriptor
  - ObjC.ModelIO.MDLVoxelArray
