name:                apple-scriptingbridge-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ScriptingBridge framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ScriptingBridge.Delegate.SBApplicationDelegate
  - ObjC.ScriptingBridge.Internal.Classes
  - ObjC.ScriptingBridge.SBApplication
  - ObjC.ScriptingBridge.SBElementArray
  - ObjC.ScriptingBridge.SBObject
