name:                apple-inputmethodkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the InputMethodKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.InputMethodKit.Delegate.IMKStateSetting
  - ObjC.InputMethodKit.IMKCandidates
  - ObjC.InputMethodKit.IMKInputController
  - ObjC.InputMethodKit.IMKServer
  - ObjC.InputMethodKit.Internal.Classes
