name:                objc-executionpolicy
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the ExecutionPolicy framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.ExecutionPolicy.EPDeveloperTool
  - ObjC.ExecutionPolicy.EPExecutionPolicy
  - ObjC.ExecutionPolicy.Enums
  - ObjC.ExecutionPolicy.Internal.Classes
  - ObjC.ExecutionPolicy.Internal.Enums
