name:                apple-intentsui-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the IntentsUI framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-foundation-gen
- apple-intents-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.IntentsUI.Delegate.INUIAddVoiceShortcutButtonDelegate
  - ObjC.IntentsUI.Delegate.INUIAddVoiceShortcutViewControllerDelegate
  - ObjC.IntentsUI.Delegate.INUIEditVoiceShortcutViewControllerDelegate
  - ObjC.IntentsUI.Enums
  - ObjC.IntentsUI.INUIAddVoiceShortcutButton
  - ObjC.IntentsUI.INUIAddVoiceShortcutViewController
  - ObjC.IntentsUI.INUIEditVoiceShortcutViewController
  - ObjC.IntentsUI.Internal.Classes
  - ObjC.IntentsUI.Internal.Enums
