name:                objc-foundation
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Foundation framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-automator
- objc-cloudkit
- objc-corefoundation
- objc-discrecording
- objc-discrecordingui
- objc-exceptionhandling
- objc-gameplaykit
- objc-iobluetooth
- objc-networkextension
- objc-quartz
- objc-quartzcore
- objc-quicklookui
- objc-securityinterface
- objc-syncservices
- objc-uniformtypeidentifiers

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Foundation.Enums
  - ObjC.Foundation.Internal.Classes
  - ObjC.Foundation.Internal.Enums
  - ObjC.Foundation.Internal.Structs
  - ObjC.Foundation.NSAffineTransform
  - ObjC.Foundation.NSAppleEventDescriptor
  - ObjC.Foundation.NSAppleEventManager
  - ObjC.Foundation.NSAppleScript
  - ObjC.Foundation.NSArchiver
  - ObjC.Foundation.NSArray
  - ObjC.Foundation.NSAssertionHandler
  - ObjC.Foundation.NSAttributedString
  - ObjC.Foundation.NSAttributedStringMarkdownParsingOptions
  - ObjC.Foundation.NSAttributedStringMarkdownSourcePosition
  - ObjC.Foundation.NSAutoreleasePool
  - ObjC.Foundation.NSBackgroundActivityScheduler
  - ObjC.Foundation.NSBlockOperation
  - ObjC.Foundation.NSBundle
  - ObjC.Foundation.NSBundleResourceRequest
  - ObjC.Foundation.NSByteCountFormatter
  - ObjC.Foundation.NSCache
  - ObjC.Foundation.NSCachedURLResponse
  - ObjC.Foundation.NSCalendar
  - ObjC.Foundation.NSCalendarDate
  - ObjC.Foundation.NSCharacterSet
  - ObjC.Foundation.NSClassDescription
  - ObjC.Foundation.NSCloneCommand
  - ObjC.Foundation.NSCloseCommand
  - ObjC.Foundation.NSCoder
  - ObjC.Foundation.NSComparisonPredicate
  - ObjC.Foundation.NSCompoundPredicate
  - ObjC.Foundation.NSCondition
  - ObjC.Foundation.NSConditionLock
  - ObjC.Foundation.NSConnection
  - ObjC.Foundation.NSConstantString
  - ObjC.Foundation.NSCountedSet
  - ObjC.Foundation.NSCreateCommand
  - ObjC.Foundation.NSData
  - ObjC.Foundation.NSDataDetector
  - ObjC.Foundation.NSDate
  - ObjC.Foundation.NSDateComponents
  - ObjC.Foundation.NSDateComponentsFormatter
  - ObjC.Foundation.NSDateFormatter
  - ObjC.Foundation.NSDateInterval
  - ObjC.Foundation.NSDateIntervalFormatter
  - ObjC.Foundation.NSDecimalNumber
  - ObjC.Foundation.NSDecimalNumberHandler
  - ObjC.Foundation.NSDeleteCommand
  - ObjC.Foundation.NSDictionary
  - ObjC.Foundation.NSDimension
  - ObjC.Foundation.NSDirectoryEnumerator
  - ObjC.Foundation.NSDistantObject
  - ObjC.Foundation.NSDistantObjectRequest
  - ObjC.Foundation.NSDistributedLock
  - ObjC.Foundation.NSDistributedNotificationCenter
  - ObjC.Foundation.NSEnergyFormatter
  - ObjC.Foundation.NSEnumerator
  - ObjC.Foundation.NSError
  - ObjC.Foundation.NSException
  - ObjC.Foundation.NSExpression
  - ObjC.Foundation.NSExtensionContext
  - ObjC.Foundation.NSExtensionItem
  - ObjC.Foundation.NSFileAccessIntent
  - ObjC.Foundation.NSFileCoordinator
  - ObjC.Foundation.NSFileHandle
  - ObjC.Foundation.NSFileManager
  - ObjC.Foundation.NSFileProviderService
  - ObjC.Foundation.NSFileSecurity
  - ObjC.Foundation.NSFileVersion
  - ObjC.Foundation.NSFileWrapper
  - ObjC.Foundation.NSFormatter
  - ObjC.Foundation.NSGarbageCollector
  - ObjC.Foundation.NSHTTPCookie
  - ObjC.Foundation.NSHTTPCookieStorage
  - ObjC.Foundation.NSHTTPURLResponse
  - ObjC.Foundation.NSHashTable
  - ObjC.Foundation.NSHost
  - ObjC.Foundation.NSISO8601DateFormatter
  - ObjC.Foundation.NSIndexPath
  - ObjC.Foundation.NSIndexSet
  - ObjC.Foundation.NSIndexSpecifier
  - ObjC.Foundation.NSInflectionRule
  - ObjC.Foundation.NSInflectionRuleExplicit
  - ObjC.Foundation.NSInputStream
  - ObjC.Foundation.NSInvocation
  - ObjC.Foundation.NSInvocationOperation
  - ObjC.Foundation.NSItemProvider
  - ObjC.Foundation.NSJSONSerialization
  - ObjC.Foundation.NSKeyValueSharedObservers
  - ObjC.Foundation.NSKeyValueSharedObserversSnapshot
  - ObjC.Foundation.NSKeyedArchiver
  - ObjC.Foundation.NSKeyedUnarchiver
  - ObjC.Foundation.NSLengthFormatter
  - ObjC.Foundation.NSLinguisticTagger
  - ObjC.Foundation.NSListFormatter
  - ObjC.Foundation.NSLocale
  - ObjC.Foundation.NSLocalizedNumberFormatRule
  - ObjC.Foundation.NSLock
  - ObjC.Foundation.NSLogicalTest
  - ObjC.Foundation.NSMachBootstrapServer
  - ObjC.Foundation.NSMachPort
  - ObjC.Foundation.NSMapTable
  - ObjC.Foundation.NSMassFormatter
  - ObjC.Foundation.NSMeasurement
  - ObjC.Foundation.NSMeasurementFormatter
  - ObjC.Foundation.NSMessagePort
  - ObjC.Foundation.NSMessagePortNameServer
  - ObjC.Foundation.NSMetadataItem
  - ObjC.Foundation.NSMetadataQuery
  - ObjC.Foundation.NSMetadataQueryAttributeValueTuple
  - ObjC.Foundation.NSMetadataQueryResultGroup
  - ObjC.Foundation.NSMethodSignature
  - ObjC.Foundation.NSMorphology
  - ObjC.Foundation.NSMorphologyCustomPronoun
  - ObjC.Foundation.NSMorphologyPronoun
  - ObjC.Foundation.NSMoveCommand
  - ObjC.Foundation.NSMutableArray
  - ObjC.Foundation.NSMutableAttributedString
  - ObjC.Foundation.NSMutableCharacterSet
  - ObjC.Foundation.NSMutableData
  - ObjC.Foundation.NSMutableDictionary
  - ObjC.Foundation.NSMutableIndexSet
  - ObjC.Foundation.NSMutableOrderedSet
  - ObjC.Foundation.NSMutableSet
  - ObjC.Foundation.NSMutableString
  - ObjC.Foundation.NSMutableURLRequest
  - ObjC.Foundation.NSNameSpecifier
  - ObjC.Foundation.NSNetService
  - ObjC.Foundation.NSNetServiceBrowser
  - ObjC.Foundation.NSNotification
  - ObjC.Foundation.NSNotificationCenter
  - ObjC.Foundation.NSNotificationQueue
  - ObjC.Foundation.NSNull
  - ObjC.Foundation.NSNumber
  - ObjC.Foundation.NSNumberFormatter
  - ObjC.Foundation.NSObject
  - ObjC.Foundation.NSOperation
  - ObjC.Foundation.NSOperationQueue
  - ObjC.Foundation.NSOrderedCollectionChange
  - ObjC.Foundation.NSOrderedCollectionDifference
  - ObjC.Foundation.NSOrderedSet
  - ObjC.Foundation.NSOrthography
  - ObjC.Foundation.NSOutputStream
  - ObjC.Foundation.NSPersonNameComponents
  - ObjC.Foundation.NSPersonNameComponentsFormatter
  - ObjC.Foundation.NSPipe
  - ObjC.Foundation.NSPointerArray
  - ObjC.Foundation.NSPointerFunctions
  - ObjC.Foundation.NSPort
  - ObjC.Foundation.NSPortCoder
  - ObjC.Foundation.NSPortMessage
  - ObjC.Foundation.NSPortNameServer
  - ObjC.Foundation.NSPositionalSpecifier
  - ObjC.Foundation.NSPredicate
  - ObjC.Foundation.NSPresentationIntent
  - ObjC.Foundation.NSProcessInfo
  - ObjC.Foundation.NSProgress
  - ObjC.Foundation.NSPropertyListSerialization
  - ObjC.Foundation.NSProtocolChecker
  - ObjC.Foundation.NSProxy
  - ObjC.Foundation.NSPurgeableData
  - ObjC.Foundation.NSQuitCommand
  - ObjC.Foundation.NSRangeSpecifier
  - ObjC.Foundation.NSRecursiveLock
  - ObjC.Foundation.NSRegularExpression
  - ObjC.Foundation.NSRelativeDateTimeFormatter
  - ObjC.Foundation.NSRelativeSpecifier
  - ObjC.Foundation.NSRunLoop
  - ObjC.Foundation.NSScanner
  - ObjC.Foundation.NSScriptClassDescription
  - ObjC.Foundation.NSScriptCoercionHandler
  - ObjC.Foundation.NSScriptCommand
  - ObjC.Foundation.NSScriptCommandDescription
  - ObjC.Foundation.NSScriptExecutionContext
  - ObjC.Foundation.NSScriptObjectSpecifier
  - ObjC.Foundation.NSScriptSuiteRegistry
  - ObjC.Foundation.NSScriptWhoseTest
  - ObjC.Foundation.NSSecureUnarchiveFromDataTransformer
  - ObjC.Foundation.NSSet
  - ObjC.Foundation.NSSetCommand
  - ObjC.Foundation.NSSimpleCString
  - ObjC.Foundation.NSSocketPort
  - ObjC.Foundation.NSSocketPortNameServer
  - ObjC.Foundation.NSSortDescriptor
  - ObjC.Foundation.NSSpecifierTest
  - ObjC.Foundation.NSSpellServer
  - ObjC.Foundation.NSStream
  - ObjC.Foundation.NSString
  - ObjC.Foundation.NSTask
  - ObjC.Foundation.NSTermOfAddress
  - ObjC.Foundation.NSTextCheckingResult
  - ObjC.Foundation.NSThread
  - ObjC.Foundation.NSTimeZone
  - ObjC.Foundation.NSTimer
  - ObjC.Foundation.NSURL
  - ObjC.Foundation.NSURLAuthenticationChallenge
  - ObjC.Foundation.NSURLCache
  - ObjC.Foundation.NSURLComponents
  - ObjC.Foundation.NSURLConnection
  - ObjC.Foundation.NSURLCredential
  - ObjC.Foundation.NSURLCredentialStorage
  - ObjC.Foundation.NSURLDownload
  - ObjC.Foundation.NSURLHandle
  - ObjC.Foundation.NSURLProtectionSpace
  - ObjC.Foundation.NSURLProtocol
  - ObjC.Foundation.NSURLQueryItem
  - ObjC.Foundation.NSURLRequest
  - ObjC.Foundation.NSURLResponse
  - ObjC.Foundation.NSURLSession
  - ObjC.Foundation.NSURLSessionConfiguration
  - ObjC.Foundation.NSURLSessionDataTask
  - ObjC.Foundation.NSURLSessionDownloadTask
  - ObjC.Foundation.NSURLSessionStreamTask
  - ObjC.Foundation.NSURLSessionTask
  - ObjC.Foundation.NSURLSessionTaskMetrics
  - ObjC.Foundation.NSURLSessionTaskTransactionMetrics
  - ObjC.Foundation.NSURLSessionUploadTask
  - ObjC.Foundation.NSURLSessionWebSocketMessage
  - ObjC.Foundation.NSURLSessionWebSocketTask
  - ObjC.Foundation.NSUUID
  - ObjC.Foundation.NSUbiquitousKeyValueStore
  - ObjC.Foundation.NSUnarchiver
  - ObjC.Foundation.NSUndoManager
  - ObjC.Foundation.NSUniqueIDSpecifier
  - ObjC.Foundation.NSUnit
  - ObjC.Foundation.NSUnitAcceleration
  - ObjC.Foundation.NSUnitAngle
  - ObjC.Foundation.NSUnitArea
  - ObjC.Foundation.NSUnitConcentrationMass
  - ObjC.Foundation.NSUnitConverter
  - ObjC.Foundation.NSUnitConverterLinear
  - ObjC.Foundation.NSUnitDispersion
  - ObjC.Foundation.NSUnitDuration
  - ObjC.Foundation.NSUnitElectricCharge
  - ObjC.Foundation.NSUnitElectricCurrent
  - ObjC.Foundation.NSUnitElectricPotentialDifference
  - ObjC.Foundation.NSUnitElectricResistance
  - ObjC.Foundation.NSUnitEnergy
  - ObjC.Foundation.NSUnitFrequency
  - ObjC.Foundation.NSUnitFuelEfficiency
  - ObjC.Foundation.NSUnitIlluminance
  - ObjC.Foundation.NSUnitInformationStorage
  - ObjC.Foundation.NSUnitLength
  - ObjC.Foundation.NSUnitMass
  - ObjC.Foundation.NSUnitPower
  - ObjC.Foundation.NSUnitPressure
  - ObjC.Foundation.NSUnitSpeed
  - ObjC.Foundation.NSUnitTemperature
  - ObjC.Foundation.NSUnitVolume
  - ObjC.Foundation.NSUserActivity
  - ObjC.Foundation.NSUserAppleScriptTask
  - ObjC.Foundation.NSUserAutomatorTask
  - ObjC.Foundation.NSUserDefaults
  - ObjC.Foundation.NSUserNotification
  - ObjC.Foundation.NSUserNotificationAction
  - ObjC.Foundation.NSUserNotificationCenter
  - ObjC.Foundation.NSUserScriptTask
  - ObjC.Foundation.NSUserUnixTask
  - ObjC.Foundation.NSValue
  - ObjC.Foundation.NSValueTransformer
  - ObjC.Foundation.NSWhoseSpecifier
  - ObjC.Foundation.NSXMLDTD
  - ObjC.Foundation.NSXMLDTDNode
  - ObjC.Foundation.NSXMLDocument
  - ObjC.Foundation.NSXMLElement
  - ObjC.Foundation.NSXMLNode
  - ObjC.Foundation.NSXMLParser
  - ObjC.Foundation.NSXPCCoder
  - ObjC.Foundation.NSXPCConnection
  - ObjC.Foundation.NSXPCInterface
  - ObjC.Foundation.NSXPCListener
  - ObjC.Foundation.NSXPCListenerEndpoint
  - ObjC.Foundation.OS_object
  - ObjC.Foundation.OS_os_workgroup
  - ObjC.Foundation.OS_os_workgroup_interval
  - ObjC.Foundation.OS_os_workgroup_parallel
  - ObjC.Foundation.Structs
