name:                objc-localauthentication
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the LocalAuthentication framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.LocalAuthentication.Enums
  - ObjC.LocalAuthentication.Internal.Classes
  - ObjC.LocalAuthentication.Internal.Enums
  - ObjC.LocalAuthentication.LAAuthenticationRequirement
  - ObjC.LocalAuthentication.LABiometryFallbackRequirement
  - ObjC.LocalAuthentication.LAContext
  - ObjC.LocalAuthentication.LADomainState
  - ObjC.LocalAuthentication.LADomainStateBiometry
  - ObjC.LocalAuthentication.LADomainStateCompanion
  - ObjC.LocalAuthentication.LAEnvironment
  - ObjC.LocalAuthentication.LAEnvironmentMechanism
  - ObjC.LocalAuthentication.LAEnvironmentMechanismBiometry
  - ObjC.LocalAuthentication.LAEnvironmentMechanismCompanion
  - ObjC.LocalAuthentication.LAEnvironmentMechanismUserPassword
  - ObjC.LocalAuthentication.LAEnvironmentState
  - ObjC.LocalAuthentication.LAPersistedRight
  - ObjC.LocalAuthentication.LAPrivateKey
  - ObjC.LocalAuthentication.LAPublicKey
  - ObjC.LocalAuthentication.LARight
  - ObjC.LocalAuthentication.LARightStore
  - ObjC.LocalAuthentication.LASecret
