name:                objc-cryptotokenkit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CryptoTokenKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CryptoTokenKit.Enums
  - ObjC.CryptoTokenKit.Internal.Classes
  - ObjC.CryptoTokenKit.Internal.Enums
  - ObjC.CryptoTokenKit.TKBERTLVRecord
  - ObjC.CryptoTokenKit.TKCompactTLVRecord
  - ObjC.CryptoTokenKit.TKSimpleTLVRecord
  - ObjC.CryptoTokenKit.TKSmartCard
  - ObjC.CryptoTokenKit.TKSmartCardATR
  - ObjC.CryptoTokenKit.TKSmartCardATRInterfaceGroup
  - ObjC.CryptoTokenKit.TKSmartCardPINFormat
  - ObjC.CryptoTokenKit.TKSmartCardSlot
  - ObjC.CryptoTokenKit.TKSmartCardSlotManager
  - ObjC.CryptoTokenKit.TKSmartCardSlotNFCSession
  - ObjC.CryptoTokenKit.TKSmartCardToken
  - ObjC.CryptoTokenKit.TKSmartCardTokenDriver
  - ObjC.CryptoTokenKit.TKSmartCardTokenRegistrationManager
  - ObjC.CryptoTokenKit.TKSmartCardTokenSession
  - ObjC.CryptoTokenKit.TKSmartCardUserInteraction
  - ObjC.CryptoTokenKit.TKSmartCardUserInteractionForPINOperation
  - ObjC.CryptoTokenKit.TKSmartCardUserInteractionForSecurePINChange
  - ObjC.CryptoTokenKit.TKSmartCardUserInteractionForSecurePINVerification
  - ObjC.CryptoTokenKit.TKTLVRecord
  - ObjC.CryptoTokenKit.TKToken
  - ObjC.CryptoTokenKit.TKTokenAuthOperation
  - ObjC.CryptoTokenKit.TKTokenConfiguration
  - ObjC.CryptoTokenKit.TKTokenDriver
  - ObjC.CryptoTokenKit.TKTokenDriverConfiguration
  - ObjC.CryptoTokenKit.TKTokenKeyAlgorithm
  - ObjC.CryptoTokenKit.TKTokenKeyExchangeParameters
  - ObjC.CryptoTokenKit.TKTokenKeychainCertificate
  - ObjC.CryptoTokenKit.TKTokenKeychainContents
  - ObjC.CryptoTokenKit.TKTokenKeychainItem
  - ObjC.CryptoTokenKit.TKTokenKeychainKey
  - ObjC.CryptoTokenKit.TKTokenPasswordAuthOperation
  - ObjC.CryptoTokenKit.TKTokenSession
  - ObjC.CryptoTokenKit.TKTokenSmartCardPINAuthOperation
  - ObjC.CryptoTokenKit.TKTokenWatcher
  - ObjC.CryptoTokenKit.TKTokenWatcherTokenInfo
