name:                objc-cloudkit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CloudKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-coredata
- objc-corelocation
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CloudKit.CKAcceptSharesOperation
  - ObjC.CloudKit.CKAllowedSharingOptions
  - ObjC.CloudKit.CKAsset
  - ObjC.CloudKit.CKContainer
  - ObjC.CloudKit.CKDatabaseNotification
  - ObjC.CloudKit.CKDatabaseOperation
  - ObjC.CloudKit.CKDatabaseSubscription
  - ObjC.CloudKit.CKDiscoverAllUserIdentitiesOperation
  - ObjC.CloudKit.CKDiscoverUserIdentitiesOperation
  - ObjC.CloudKit.CKFetchDatabaseChangesOperation
  - ObjC.CloudKit.CKFetchNotificationChangesOperation
  - ObjC.CloudKit.CKFetchRecordChangesOperation
  - ObjC.CloudKit.CKFetchRecordZoneChangesConfiguration
  - ObjC.CloudKit.CKFetchRecordZoneChangesOperation
  - ObjC.CloudKit.CKFetchRecordZoneChangesOptions
  - ObjC.CloudKit.CKFetchRecordZonesOperation
  - ObjC.CloudKit.CKFetchRecordsOperation
  - ObjC.CloudKit.CKFetchShareMetadataOperation
  - ObjC.CloudKit.CKFetchShareParticipantsOperation
  - ObjC.CloudKit.CKFetchSubscriptionsOperation
  - ObjC.CloudKit.CKFetchWebAuthTokenOperation
  - ObjC.CloudKit.CKLocationSortDescriptor
  - ObjC.CloudKit.CKMarkNotificationsReadOperation
  - ObjC.CloudKit.CKModifyBadgeOperation
  - ObjC.CloudKit.CKModifyRecordZonesOperation
  - ObjC.CloudKit.CKModifyRecordsOperation
  - ObjC.CloudKit.CKModifySubscriptionsOperation
  - ObjC.CloudKit.CKNotification
  - ObjC.CloudKit.CKNotificationID
  - ObjC.CloudKit.CKNotificationInfo
  - ObjC.CloudKit.CKOperation
  - ObjC.CloudKit.CKOperationConfiguration
  - ObjC.CloudKit.CKOperationGroup
  - ObjC.CloudKit.CKQuery
  - ObjC.CloudKit.CKQueryCursor
  - ObjC.CloudKit.CKQueryNotification
  - ObjC.CloudKit.CKQueryOperation
  - ObjC.CloudKit.CKQuerySubscription
  - ObjC.CloudKit.CKRecord
  - ObjC.CloudKit.CKRecordID
  - ObjC.CloudKit.CKRecordZone
  - ObjC.CloudKit.CKRecordZoneID
  - ObjC.CloudKit.CKRecordZoneNotification
  - ObjC.CloudKit.CKRecordZoneSubscription
  - ObjC.CloudKit.CKReference
  - ObjC.CloudKit.CKServerChangeToken
  - ObjC.CloudKit.CKShare
  - ObjC.CloudKit.CKShareAccessRequester
  - ObjC.CloudKit.CKShareBlockedIdentity
  - ObjC.CloudKit.CKShareMetadata
  - ObjC.CloudKit.CKShareParticipant
  - ObjC.CloudKit.CKShareRequestAccessOperation
  - ObjC.CloudKit.CKSubscription
  - ObjC.CloudKit.CKSyncEngine
  - ObjC.CloudKit.CKSyncEngineAccountChangeEvent
  - ObjC.CloudKit.CKSyncEngineConfiguration
  - ObjC.CloudKit.CKSyncEngineDidFetchChangesEvent
  - ObjC.CloudKit.CKSyncEngineDidFetchRecordZoneChangesEvent
  - ObjC.CloudKit.CKSyncEngineDidSendChangesEvent
  - ObjC.CloudKit.CKSyncEngineEvent
  - ObjC.CloudKit.CKSyncEngineFailedRecordSave
  - ObjC.CloudKit.CKSyncEngineFailedZoneSave
  - ObjC.CloudKit.CKSyncEngineFetchChangesContext
  - ObjC.CloudKit.CKSyncEngineFetchChangesOptions
  - ObjC.CloudKit.CKSyncEngineFetchChangesScope
  - ObjC.CloudKit.CKSyncEngineFetchedDatabaseChangesEvent
  - ObjC.CloudKit.CKSyncEngineFetchedRecordDeletion
  - ObjC.CloudKit.CKSyncEngineFetchedRecordZoneChangesEvent
  - ObjC.CloudKit.CKSyncEngineFetchedZoneDeletion
  - ObjC.CloudKit.CKSyncEnginePendingDatabaseChange
  - ObjC.CloudKit.CKSyncEnginePendingRecordZoneChange
  - ObjC.CloudKit.CKSyncEnginePendingZoneDelete
  - ObjC.CloudKit.CKSyncEnginePendingZoneSave
  - ObjC.CloudKit.CKSyncEngineRecordZoneChangeBatch
  - ObjC.CloudKit.CKSyncEngineSendChangesContext
  - ObjC.CloudKit.CKSyncEngineSendChangesOptions
  - ObjC.CloudKit.CKSyncEngineSendChangesScope
  - ObjC.CloudKit.CKSyncEngineSentDatabaseChangesEvent
  - ObjC.CloudKit.CKSyncEngineSentRecordZoneChangesEvent
  - ObjC.CloudKit.CKSyncEngineState
  - ObjC.CloudKit.CKSyncEngineStateSerialization
  - ObjC.CloudKit.CKSyncEngineStateUpdateEvent
  - ObjC.CloudKit.CKSyncEngineWillFetchChangesEvent
  - ObjC.CloudKit.CKSyncEngineWillFetchRecordZoneChangesEvent
  - ObjC.CloudKit.CKSyncEngineWillSendChangesEvent
  - ObjC.CloudKit.CKSystemSharingUIObserver
  - ObjC.CloudKit.CKUserIdentity
  - ObjC.CloudKit.CKUserIdentityLookupInfo
  - ObjC.CloudKit.Enums
  - ObjC.CloudKit.Internal.Classes
  - ObjC.CloudKit.Internal.Enums
  - ObjC.CloudKit.NSItemProvider
