name:                apple-nearbyinteraction-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the NearbyInteraction framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.NearbyInteraction.Delegate.NIDeviceCapability
  - ObjC.NearbyInteraction.Delegate.NISessionDelegate
  - ObjC.NearbyInteraction.Enums
  - ObjC.NearbyInteraction.Internal.Classes
  - ObjC.NearbyInteraction.Internal.Enums
  - ObjC.NearbyInteraction.NIAlgorithmConvergence
  - ObjC.NearbyInteraction.NIConfiguration
  - ObjC.NearbyInteraction.NIDLTDOAConfiguration
  - ObjC.NearbyInteraction.NIDLTDOAMeasurement
  - ObjC.NearbyInteraction.NIDiscoveryToken
  - ObjC.NearbyInteraction.NINearbyAccessoryConfiguration
  - ObjC.NearbyInteraction.NINearbyObject
  - ObjC.NearbyInteraction.NINearbyPeerConfiguration
  - ObjC.NearbyInteraction.NISession
