name:                apple-authenticationservices-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AuthenticationServices framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-appkit-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationController
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationExtensionContext
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationReplacePasswordWithSignInWithAppleRequest
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationRequest
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationUpgradePasswordToStrongPasswordRequest
  - ObjC.AuthenticationServices.ASAccountAuthenticationModificationViewController
  - ObjC.AuthenticationServices.ASAuthorization
  - ObjC.AuthenticationServices.ASAuthorizationAppleIDButton
  - ObjC.AuthenticationServices.ASAuthorizationAppleIDCredential
  - ObjC.AuthenticationServices.ASAuthorizationAppleIDProvider
  - ObjC.AuthenticationServices.ASAuthorizationAppleIDRequest
  - ObjC.AuthenticationServices.ASAuthorizationController
  - ObjC.AuthenticationServices.ASAuthorizationOpenIDRequest
  - ObjC.AuthenticationServices.ASAuthorizationPasswordProvider
  - ObjC.AuthenticationServices.ASAuthorizationPasswordRequest
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialAssertion
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialAssertionRequest
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialDescriptor
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialProvider
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialRegistration
  - ObjC.AuthenticationServices.ASAuthorizationPlatformPublicKeyCredentialRegistrationRequest
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionAuthorizationRequest
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionAuthorizationResult
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionKerberosMapping
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionLoginConfiguration
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionLoginManager
  - ObjC.AuthenticationServices.ASAuthorizationProviderExtensionUserLoginConfiguration
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialLargeBlobAssertionInput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialLargeBlobAssertionOutput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialLargeBlobRegistrationInput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialLargeBlobRegistrationOutput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFAssertionInput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFAssertionInputValues
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFAssertionOutput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFRegistrationInput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialPRFRegistrationOutput
  - ObjC.AuthenticationServices.ASAuthorizationPublicKeyCredentialParameters
  - ObjC.AuthenticationServices.ASAuthorizationRequest
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialAssertion
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialAssertionRequest
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialDescriptor
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialProvider
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialRegistration
  - ObjC.AuthenticationServices.ASAuthorizationSecurityKeyPublicKeyCredentialRegistrationRequest
  - ObjC.AuthenticationServices.ASAuthorizationSingleSignOnCredential
  - ObjC.AuthenticationServices.ASAuthorizationSingleSignOnProvider
  - ObjC.AuthenticationServices.ASAuthorizationSingleSignOnRequest
  - ObjC.AuthenticationServices.ASAuthorizationWebBrowserPlatformPublicKeyCredential
  - ObjC.AuthenticationServices.ASAuthorizationWebBrowserPublicKeyCredentialManager
  - ObjC.AuthenticationServices.ASCredentialIdentityStore
  - ObjC.AuthenticationServices.ASCredentialIdentityStoreState
  - ObjC.AuthenticationServices.ASCredentialProviderExtensionContext
  - ObjC.AuthenticationServices.ASCredentialProviderViewController
  - ObjC.AuthenticationServices.ASCredentialServiceIdentifier
  - ObjC.AuthenticationServices.ASGeneratePasswordsRequest
  - ObjC.AuthenticationServices.ASGeneratedPassword
  - ObjC.AuthenticationServices.ASOneTimeCodeCredential
  - ObjC.AuthenticationServices.ASOneTimeCodeCredentialIdentity
  - ObjC.AuthenticationServices.ASOneTimeCodeCredentialRequest
  - ObjC.AuthenticationServices.ASPasskeyAssertionCredential
  - ObjC.AuthenticationServices.ASPasskeyAssertionCredentialExtensionInput
  - ObjC.AuthenticationServices.ASPasskeyAssertionCredentialExtensionOutput
  - ObjC.AuthenticationServices.ASPasskeyCredentialIdentity
  - ObjC.AuthenticationServices.ASPasskeyCredentialRequest
  - ObjC.AuthenticationServices.ASPasskeyCredentialRequestParameters
  - ObjC.AuthenticationServices.ASPasskeyRegistrationCredential
  - ObjC.AuthenticationServices.ASPasskeyRegistrationCredentialExtensionInput
  - ObjC.AuthenticationServices.ASPasskeyRegistrationCredentialExtensionOutput
  - ObjC.AuthenticationServices.ASPasswordCredential
  - ObjC.AuthenticationServices.ASPasswordCredentialIdentity
  - ObjC.AuthenticationServices.ASPasswordCredentialRequest
  - ObjC.AuthenticationServices.ASPublicKeyCredentialClientData
  - ObjC.AuthenticationServices.ASSavePasswordRequest
  - ObjC.AuthenticationServices.ASSettingsHelper
  - ObjC.AuthenticationServices.ASWebAuthenticationSession
  - ObjC.AuthenticationServices.ASWebAuthenticationSessionCallback
  - ObjC.AuthenticationServices.ASWebAuthenticationSessionRequest
  - ObjC.AuthenticationServices.ASWebAuthenticationSessionWebBrowserSessionManager
  - ObjC.AuthenticationServices.Delegate.ASAccountAuthenticationModificationControllerDelegate
  - ObjC.AuthenticationServices.Delegate.ASAccountAuthenticationModificationControllerPresentationContextProviding
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationControllerDelegate
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationControllerPresentationContextProviding
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationProviderExtensionAuthorizationRequestHandler
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationProviderExtensionRegistrationHandler
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationPublicKeyCredentialAssertion
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationPublicKeyCredentialAssertionRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationPublicKeyCredentialRegistration
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationPublicKeyCredentialRegistrationRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserExternallyAuthenticatableRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserPlatformPublicKeyCredentialAssertionRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserPlatformPublicKeyCredentialProvider
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserPlatformPublicKeyCredentialRegistrationRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialAssertionRequest
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialProvider
  - ObjC.AuthenticationServices.Delegate.ASAuthorizationWebBrowserSecurityKeyPublicKeyCredentialRegistrationRequest
  - ObjC.AuthenticationServices.Delegate.ASCredentialRequest
  - ObjC.AuthenticationServices.Delegate.ASPublicKeyCredential
  - ObjC.AuthenticationServices.Delegate.ASWebAuthenticationPresentationContextProviding
  - ObjC.AuthenticationServices.Delegate.ASWebAuthenticationSessionRequestDelegate
  - ObjC.AuthenticationServices.Delegate.ASWebAuthenticationSessionWebBrowserSessionHandling
  - ObjC.AuthenticationServices.Enums
  - ObjC.AuthenticationServices.Internal.Classes
  - ObjC.AuthenticationServices.Internal.Enums
