name:                objc-localauthenticationembeddedui
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the LocalAuthenticationEmbeddedUI framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation
- objc-localauthentication

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.LocalAuthenticationEmbeddedUI.Internal.Classes
  - ObjC.LocalAuthenticationEmbeddedUI.LAAuthenticationView
  - ObjC.LocalAuthenticationEmbeddedUI.LARight
