name:                objc-videotoolbox
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the VideoToolbox framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.VideoToolbox.Enums
  - ObjC.VideoToolbox.Internal.Classes
  - ObjC.VideoToolbox.Internal.Enums
  - ObjC.VideoToolbox.Internal.Structs
  - ObjC.VideoToolbox.Structs
  - ObjC.VideoToolbox.VTFrameProcessor
  - ObjC.VideoToolbox.VTFrameProcessorFrame
  - ObjC.VideoToolbox.VTFrameProcessorOpticalFlow
  - ObjC.VideoToolbox.VTFrameRateConversionConfiguration
  - ObjC.VideoToolbox.VTFrameRateConversionParameters
  - ObjC.VideoToolbox.VTLowLatencyFrameInterpolationConfiguration
  - ObjC.VideoToolbox.VTLowLatencyFrameInterpolationParameters
  - ObjC.VideoToolbox.VTLowLatencySuperResolutionScalerConfiguration
  - ObjC.VideoToolbox.VTLowLatencySuperResolutionScalerParameters
  - ObjC.VideoToolbox.VTMotionBlurConfiguration
  - ObjC.VideoToolbox.VTMotionBlurParameters
  - ObjC.VideoToolbox.VTOpticalFlowConfiguration
  - ObjC.VideoToolbox.VTOpticalFlowParameters
  - ObjC.VideoToolbox.VTSuperResolutionScalerConfiguration
  - ObjC.VideoToolbox.VTSuperResolutionScalerParameters
  - ObjC.VideoToolbox.VTTemporalNoiseFilterConfiguration
  - ObjC.VideoToolbox.VTTemporalNoiseFilterParameters
