name:                apple-appkit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AppKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-coredata-gen
- apple-coreimage-gen
- apple-foundation-gen
- apple-quartzcore-gen
- apple-symbols-gen
- apple-uniformtypeidentifiers-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AppKit.Delegate.NSAccessibility
  - ObjC.AppKit.Delegate.NSAccessibilityButton
  - ObjC.AppKit.Delegate.NSAccessibilityCheckBox
  - ObjC.AppKit.Delegate.NSAccessibilityColor
  - ObjC.AppKit.Delegate.NSAccessibilityContainsTransientUI
  - ObjC.AppKit.Delegate.NSAccessibilityCustomRotorItemSearchDelegate
  - ObjC.AppKit.Delegate.NSAccessibilityElement
  - ObjC.AppKit.Delegate.NSAccessibilityImage
  - ObjC.AppKit.Delegate.NSAccessibilityLayoutArea
  - ObjC.AppKit.Delegate.NSAccessibilityNavigableStaticText
  - ObjC.AppKit.Delegate.NSAccessibilityProgressIndicator
  - ObjC.AppKit.Delegate.NSAccessibilityRadioButton
  - ObjC.AppKit.Delegate.NSAccessibilityRow
  - ObjC.AppKit.Delegate.NSAccessibilitySlider
  - ObjC.AppKit.Delegate.NSAccessibilityStaticText
  - ObjC.AppKit.Delegate.NSAccessibilityStepper
  - ObjC.AppKit.Delegate.NSAccessibilitySwitch
  - ObjC.AppKit.Delegate.NSAccessibilityTable
  - ObjC.AppKit.Delegate.NSAlertDelegate
  - ObjC.AppKit.Delegate.NSAnimatablePropertyContainer
  - ObjC.AppKit.Delegate.NSAnimationDelegate
  - ObjC.AppKit.Delegate.NSAppearanceCustomization
  - ObjC.AppKit.Delegate.NSApplicationDelegate
  - ObjC.AppKit.Delegate.NSBrowserDelegate
  - ObjC.AppKit.Delegate.NSCandidateListTouchBarItemDelegate
  - ObjC.AppKit.Delegate.NSChangeSpelling
  - ObjC.AppKit.Delegate.NSCloudSharingServiceDelegate
  - ObjC.AppKit.Delegate.NSCloudSharingValidation
  - ObjC.AppKit.Delegate.NSCollectionLayoutEnvironment
  - ObjC.AppKit.Delegate.NSCollectionLayoutVisibleItem
  - ObjC.AppKit.Delegate.NSCollectionViewDataSource
  - ObjC.AppKit.Delegate.NSCollectionViewDelegate
  - ObjC.AppKit.Delegate.NSCollectionViewDelegateFlowLayout
  - ObjC.AppKit.Delegate.NSCollectionViewElement
  - ObjC.AppKit.Delegate.NSCollectionViewPrefetching
  - ObjC.AppKit.Delegate.NSCollectionViewSectionHeaderView
  - ObjC.AppKit.Delegate.NSColorChanging
  - ObjC.AppKit.Delegate.NSColorPickingCustom
  - ObjC.AppKit.Delegate.NSColorPickingDefault
  - ObjC.AppKit.Delegate.NSComboBoxCellDataSource
  - ObjC.AppKit.Delegate.NSComboBoxDataSource
  - ObjC.AppKit.Delegate.NSComboBoxDelegate
  - ObjC.AppKit.Delegate.NSControlTextEditingDelegate
  - ObjC.AppKit.Delegate.NSDatePickerCellDelegate
  - ObjC.AppKit.Delegate.NSDockTilePlugIn
  - ObjC.AppKit.Delegate.NSDraggingDestination
  - ObjC.AppKit.Delegate.NSDraggingInfo
  - ObjC.AppKit.Delegate.NSDrawerDelegate
  - ObjC.AppKit.Delegate.NSEditor
  - ObjC.AppKit.Delegate.NSEditorRegistration
  - ObjC.AppKit.Delegate.NSFilePromiseProviderDelegate
  - ObjC.AppKit.Delegate.NSFontChanging
  - ObjC.AppKit.Delegate.NSGestureRecognizerDelegate
  - ObjC.AppKit.Delegate.NSGlyphStorage
  - ObjC.AppKit.Delegate.NSIgnoreMisspelledWords
  - ObjC.AppKit.Delegate.NSImageDelegate
  - ObjC.AppKit.Delegate.NSInputServiceProvider
  - ObjC.AppKit.Delegate.NSLayoutManagerDelegate
  - ObjC.AppKit.Delegate.NSMenuDelegate
  - ObjC.AppKit.Delegate.NSMenuItemValidation
  - ObjC.AppKit.Delegate.NSOpenSavePanelDelegate
  - ObjC.AppKit.Delegate.NSOutlineViewDataSource
  - ObjC.AppKit.Delegate.NSOutlineViewDelegate
  - ObjC.AppKit.Delegate.NSPageControllerDelegate
  - ObjC.AppKit.Delegate.NSPasteboardItemDataProvider
  - ObjC.AppKit.Delegate.NSPasteboardReading
  - ObjC.AppKit.Delegate.NSPasteboardTypeOwner
  - ObjC.AppKit.Delegate.NSPathCellDelegate
  - ObjC.AppKit.Delegate.NSPathControlDelegate
  - ObjC.AppKit.Delegate.NSPopoverDelegate
  - ObjC.AppKit.Delegate.NSPreviewRepresentableActivityItem
  - ObjC.AppKit.Delegate.NSPrintPanelAccessorizing
  - ObjC.AppKit.Delegate.NSRuleEditorDelegate
  - ObjC.AppKit.Delegate.NSScrubberDataSource
  - ObjC.AppKit.Delegate.NSSearchFieldDelegate
  - ObjC.AppKit.Delegate.NSSeguePerforming
  - ObjC.AppKit.Delegate.NSServicesMenuRequestor
  - ObjC.AppKit.Delegate.NSSharingServiceDelegate
  - ObjC.AppKit.Delegate.NSSharingServicePickerDelegate
  - ObjC.AppKit.Delegate.NSSharingServicePickerToolbarItemDelegate
  - ObjC.AppKit.Delegate.NSSharingServicePickerTouchBarItemDelegate
  - ObjC.AppKit.Delegate.NSSoundDelegate
  - ObjC.AppKit.Delegate.NSSpeechRecognizerDelegate
  - ObjC.AppKit.Delegate.NSSpeechSynthesizerDelegate
  - ObjC.AppKit.Delegate.NSSplitViewDelegate
  - ObjC.AppKit.Delegate.NSSpringLoadingDestination
  - ObjC.AppKit.Delegate.NSStackViewDelegate
  - ObjC.AppKit.Delegate.NSStandardKeyBindingResponding
  - ObjC.AppKit.Delegate.NSTabViewDelegate
  - ObjC.AppKit.Delegate.NSTableViewDataSource
  - ObjC.AppKit.Delegate.NSTableViewDelegate
  - ObjC.AppKit.Delegate.NSTextAttachmentLayout
  - ObjC.AppKit.Delegate.NSTextCheckingClient
  - ObjC.AppKit.Delegate.NSTextContent
  - ObjC.AppKit.Delegate.NSTextContentManagerDelegate
  - ObjC.AppKit.Delegate.NSTextDelegate
  - ObjC.AppKit.Delegate.NSTextElementProvider
  - ObjC.AppKit.Delegate.NSTextFieldDelegate
  - ObjC.AppKit.Delegate.NSTextFinderBarContainer
  - ObjC.AppKit.Delegate.NSTextFinderClient
  - ObjC.AppKit.Delegate.NSTextInput
  - ObjC.AppKit.Delegate.NSTextInputClient
  - ObjC.AppKit.Delegate.NSTextLayoutManagerDelegate
  - ObjC.AppKit.Delegate.NSTextViewDelegate
  - ObjC.AppKit.Delegate.NSTextViewportLayoutControllerDelegate
  - ObjC.AppKit.Delegate.NSTokenFieldCellDelegate
  - ObjC.AppKit.Delegate.NSTokenFieldDelegate
  - ObjC.AppKit.Delegate.NSToolbarDelegate
  - ObjC.AppKit.Delegate.NSToolbarItemValidation
  - ObjC.AppKit.Delegate.NSTouchBarDelegate
  - ObjC.AppKit.Delegate.NSTouchBarProvider
  - ObjC.AppKit.Delegate.NSUserInterfaceCompression
  - ObjC.AppKit.Delegate.NSUserInterfaceItemIdentification
  - ObjC.AppKit.Delegate.NSUserInterfaceItemSearching
  - ObjC.AppKit.Delegate.NSUserInterfaceValidations
  - ObjC.AppKit.Delegate.NSValidatedUserInterfaceItem
  - ObjC.AppKit.Delegate.NSViewControllerPresentationAnimator
  - ObjC.AppKit.Delegate.NSViewLayerContentScaleDelegate
  - ObjC.AppKit.Delegate.NSWindowDelegate
  - ObjC.AppKit.Enums
  - ObjC.AppKit.Internal.Classes
  - ObjC.AppKit.Internal.Enums
  - ObjC.AppKit.Internal.Structs
  - ObjC.AppKit.NSATSTypesetter
  - ObjC.AppKit.NSAccessibilityCustomAction
  - ObjC.AppKit.NSAccessibilityCustomRotor
  - ObjC.AppKit.NSAccessibilityCustomRotorItemResult
  - ObjC.AppKit.NSAccessibilityCustomRotorSearchParameters
  - ObjC.AppKit.NSAccessibilityElement
  - ObjC.AppKit.NSActionCell
  - ObjC.AppKit.NSAdaptiveImageGlyph
  - ObjC.AppKit.NSAlert
  - ObjC.AppKit.NSAlignmentFeedbackFilter
  - ObjC.AppKit.NSAnimation
  - ObjC.AppKit.NSAnimationContext
  - ObjC.AppKit.NSAppearance
  - ObjC.AppKit.NSApplication
  - ObjC.AppKit.NSArrayController
  - ObjC.AppKit.NSBackgroundExtensionView
  - ObjC.AppKit.NSBezierPath
  - ObjC.AppKit.NSBindingSelectionMarker
  - ObjC.AppKit.NSBitmapImageRep
  - ObjC.AppKit.NSBox
  - ObjC.AppKit.NSBrowser
  - ObjC.AppKit.NSBrowserCell
  - ObjC.AppKit.NSButton
  - ObjC.AppKit.NSButtonCell
  - ObjC.AppKit.NSButtonTouchBarItem
  - ObjC.AppKit.NSCIImageRep
  - ObjC.AppKit.NSCachedImageRep
  - ObjC.AppKit.NSCandidateListTouchBarItem
  - ObjC.AppKit.NSCell
  - ObjC.AppKit.NSClickGestureRecognizer
  - ObjC.AppKit.NSClipView
  - ObjC.AppKit.NSCollectionLayoutAnchor
  - ObjC.AppKit.NSCollectionLayoutBoundarySupplementaryItem
  - ObjC.AppKit.NSCollectionLayoutDecorationItem
  - ObjC.AppKit.NSCollectionLayoutDimension
  - ObjC.AppKit.NSCollectionLayoutEdgeSpacing
  - ObjC.AppKit.NSCollectionLayoutGroup
  - ObjC.AppKit.NSCollectionLayoutGroupCustomItem
  - ObjC.AppKit.NSCollectionLayoutItem
  - ObjC.AppKit.NSCollectionLayoutSection
  - ObjC.AppKit.NSCollectionLayoutSize
  - ObjC.AppKit.NSCollectionLayoutSpacing
  - ObjC.AppKit.NSCollectionLayoutSupplementaryItem
  - ObjC.AppKit.NSCollectionView
  - ObjC.AppKit.NSCollectionViewCompositionalLayout
  - ObjC.AppKit.NSCollectionViewCompositionalLayoutConfiguration
  - ObjC.AppKit.NSCollectionViewDiffableDataSource
  - ObjC.AppKit.NSCollectionViewFlowLayout
  - ObjC.AppKit.NSCollectionViewFlowLayoutInvalidationContext
  - ObjC.AppKit.NSCollectionViewGridLayout
  - ObjC.AppKit.NSCollectionViewItem
  - ObjC.AppKit.NSCollectionViewLayout
  - ObjC.AppKit.NSCollectionViewLayoutAttributes
  - ObjC.AppKit.NSCollectionViewLayoutInvalidationContext
  - ObjC.AppKit.NSCollectionViewTransitionLayout
  - ObjC.AppKit.NSCollectionViewUpdateItem
  - ObjC.AppKit.NSColor
  - ObjC.AppKit.NSColorList
  - ObjC.AppKit.NSColorPanel
  - ObjC.AppKit.NSColorPicker
  - ObjC.AppKit.NSColorPickerTouchBarItem
  - ObjC.AppKit.NSColorSampler
  - ObjC.AppKit.NSColorSpace
  - ObjC.AppKit.NSColorWell
  - ObjC.AppKit.NSComboBox
  - ObjC.AppKit.NSComboBoxCell
  - ObjC.AppKit.NSComboButton
  - ObjC.AppKit.NSControl
  - ObjC.AppKit.NSController
  - ObjC.AppKit.NSCursor
  - ObjC.AppKit.NSCustomImageRep
  - ObjC.AppKit.NSCustomTouchBarItem
  - ObjC.AppKit.NSDataAsset
  - ObjC.AppKit.NSDatePicker
  - ObjC.AppKit.NSDatePickerCell
  - ObjC.AppKit.NSDictionaryController
  - ObjC.AppKit.NSDictionaryControllerKeyValuePair
  - ObjC.AppKit.NSDiffableDataSourceSnapshot
  - ObjC.AppKit.NSDockTile
  - ObjC.AppKit.NSDocument
  - ObjC.AppKit.NSDocumentController
  - ObjC.AppKit.NSDraggingImageComponent
  - ObjC.AppKit.NSDraggingItem
  - ObjC.AppKit.NSDraggingSession
  - ObjC.AppKit.NSDrawer
  - ObjC.AppKit.NSEPSImageRep
  - ObjC.AppKit.NSEvent
  - ObjC.AppKit.NSFilePromiseProvider
  - ObjC.AppKit.NSFilePromiseReceiver
  - ObjC.AppKit.NSFont
  - ObjC.AppKit.NSFontAssetRequest
  - ObjC.AppKit.NSFontCollection
  - ObjC.AppKit.NSFontDescriptor
  - ObjC.AppKit.NSFontManager
  - ObjC.AppKit.NSFontPanel
  - ObjC.AppKit.NSForm
  - ObjC.AppKit.NSFormCell
  - ObjC.AppKit.NSGestureRecognizer
  - ObjC.AppKit.NSGlassEffectContainerView
  - ObjC.AppKit.NSGlassEffectView
  - ObjC.AppKit.NSGlyphGenerator
  - ObjC.AppKit.NSGlyphInfo
  - ObjC.AppKit.NSGradient
  - ObjC.AppKit.NSGraphicsContext
  - ObjC.AppKit.NSGridCell
  - ObjC.AppKit.NSGridColumn
  - ObjC.AppKit.NSGridRow
  - ObjC.AppKit.NSGridView
  - ObjC.AppKit.NSGroupTouchBarItem
  - ObjC.AppKit.NSHapticFeedbackManager
  - ObjC.AppKit.NSHelpManager
  - ObjC.AppKit.NSImage
  - ObjC.AppKit.NSImageCell
  - ObjC.AppKit.NSImageRep
  - ObjC.AppKit.NSImageSymbolConfiguration
  - ObjC.AppKit.NSImageView
  - ObjC.AppKit.NSInputManager
  - ObjC.AppKit.NSInputServer
  - ObjC.AppKit.NSItemBadge
  - ObjC.AppKit.NSLayoutAnchor
  - ObjC.AppKit.NSLayoutConstraint
  - ObjC.AppKit.NSLayoutDimension
  - ObjC.AppKit.NSLayoutGuide
  - ObjC.AppKit.NSLayoutManager
  - ObjC.AppKit.NSLayoutXAxisAnchor
  - ObjC.AppKit.NSLayoutYAxisAnchor
  - ObjC.AppKit.NSLevelIndicator
  - ObjC.AppKit.NSLevelIndicatorCell
  - ObjC.AppKit.NSMagnificationGestureRecognizer
  - ObjC.AppKit.NSMatrix
  - ObjC.AppKit.NSMediaLibraryBrowserController
  - ObjC.AppKit.NSMenu
  - ObjC.AppKit.NSMenuItem
  - ObjC.AppKit.NSMenuItemBadge
  - ObjC.AppKit.NSMenuItemCell
  - ObjC.AppKit.NSMenuToolbarItem
  - ObjC.AppKit.NSMovie
  - ObjC.AppKit.NSMutableFontCollection
  - ObjC.AppKit.NSMutableParagraphStyle
  - ObjC.AppKit.NSNib
  - ObjC.AppKit.NSObjectController
  - ObjC.AppKit.NSOpenGLContext
  - ObjC.AppKit.NSOpenGLLayer
  - ObjC.AppKit.NSOpenGLPixelBuffer
  - ObjC.AppKit.NSOpenGLPixelFormat
  - ObjC.AppKit.NSOpenGLView
  - ObjC.AppKit.NSOpenPanel
  - ObjC.AppKit.NSOutlineView
  - ObjC.AppKit.NSPDFImageRep
  - ObjC.AppKit.NSPDFInfo
  - ObjC.AppKit.NSPDFPanel
  - ObjC.AppKit.NSPICTImageRep
  - ObjC.AppKit.NSPageController
  - ObjC.AppKit.NSPageLayout
  - ObjC.AppKit.NSPanGestureRecognizer
  - ObjC.AppKit.NSPanel
  - ObjC.AppKit.NSParagraphStyle
  - ObjC.AppKit.NSPasteboard
  - ObjC.AppKit.NSPasteboardItem
  - ObjC.AppKit.NSPathCell
  - ObjC.AppKit.NSPathComponentCell
  - ObjC.AppKit.NSPathControl
  - ObjC.AppKit.NSPathControlItem
  - ObjC.AppKit.NSPersistentDocument
  - ObjC.AppKit.NSPickerTouchBarItem
  - ObjC.AppKit.NSPopUpButton
  - ObjC.AppKit.NSPopUpButtonCell
  - ObjC.AppKit.NSPopover
  - ObjC.AppKit.NSPopoverTouchBarItem
  - ObjC.AppKit.NSPredicateEditor
  - ObjC.AppKit.NSPredicateEditorRowTemplate
  - ObjC.AppKit.NSPressGestureRecognizer
  - ObjC.AppKit.NSPressureConfiguration
  - ObjC.AppKit.NSPreviewRepresentingActivityItem
  - ObjC.AppKit.NSPrintInfo
  - ObjC.AppKit.NSPrintOperation
  - ObjC.AppKit.NSPrintPanel
  - ObjC.AppKit.NSPrinter
  - ObjC.AppKit.NSProgressIndicator
  - ObjC.AppKit.NSResponder
  - ObjC.AppKit.NSRotationGestureRecognizer
  - ObjC.AppKit.NSRuleEditor
  - ObjC.AppKit.NSRulerMarker
  - ObjC.AppKit.NSRulerView
  - ObjC.AppKit.NSRunningApplication
  - ObjC.AppKit.NSSavePanel
  - ObjC.AppKit.NSScreen
  - ObjC.AppKit.NSScrollEdgeEffectStyle
  - ObjC.AppKit.NSScrollView
  - ObjC.AppKit.NSScroller
  - ObjC.AppKit.NSScrubber
  - ObjC.AppKit.NSScrubberArrangedView
  - ObjC.AppKit.NSScrubberFlowLayout
  - ObjC.AppKit.NSScrubberImageItemView
  - ObjC.AppKit.NSScrubberItemView
  - ObjC.AppKit.NSScrubberLayout
  - ObjC.AppKit.NSScrubberLayoutAttributes
  - ObjC.AppKit.NSScrubberProportionalLayout
  - ObjC.AppKit.NSScrubberSelectionStyle
  - ObjC.AppKit.NSScrubberSelectionView
  - ObjC.AppKit.NSScrubberTextItemView
  - ObjC.AppKit.NSSearchField
  - ObjC.AppKit.NSSearchFieldCell
  - ObjC.AppKit.NSSearchToolbarItem
  - ObjC.AppKit.NSSecureTextField
  - ObjC.AppKit.NSSecureTextFieldCell
  - ObjC.AppKit.NSSegmentedCell
  - ObjC.AppKit.NSSegmentedControl
  - ObjC.AppKit.NSShadow
  - ObjC.AppKit.NSSharingCollaborationModeRestriction
  - ObjC.AppKit.NSSharingService
  - ObjC.AppKit.NSSharingServicePicker
  - ObjC.AppKit.NSSharingServicePickerToolbarItem
  - ObjC.AppKit.NSSharingServicePickerTouchBarItem
  - ObjC.AppKit.NSSlider
  - ObjC.AppKit.NSSliderAccessory
  - ObjC.AppKit.NSSliderAccessoryBehavior
  - ObjC.AppKit.NSSliderCell
  - ObjC.AppKit.NSSliderTouchBarItem
  - ObjC.AppKit.NSSound
  - ObjC.AppKit.NSSpeechRecognizer
  - ObjC.AppKit.NSSpeechSynthesizer
  - ObjC.AppKit.NSSpellChecker
  - ObjC.AppKit.NSSplitView
  - ObjC.AppKit.NSSplitViewController
  - ObjC.AppKit.NSSplitViewItem
  - ObjC.AppKit.NSSplitViewItemAccessoryViewController
  - ObjC.AppKit.NSStackView
  - ObjC.AppKit.NSStatusBar
  - ObjC.AppKit.NSStatusBarButton
  - ObjC.AppKit.NSStatusItem
  - ObjC.AppKit.NSStepper
  - ObjC.AppKit.NSStepperCell
  - ObjC.AppKit.NSStepperTouchBarItem
  - ObjC.AppKit.NSStoryboard
  - ObjC.AppKit.NSStoryboardSegue
  - ObjC.AppKit.NSStringDrawingContext
  - ObjC.AppKit.NSSwitch
  - ObjC.AppKit.NSTabView
  - ObjC.AppKit.NSTabViewController
  - ObjC.AppKit.NSTabViewItem
  - ObjC.AppKit.NSTableCellView
  - ObjC.AppKit.NSTableColumn
  - ObjC.AppKit.NSTableHeaderCell
  - ObjC.AppKit.NSTableHeaderView
  - ObjC.AppKit.NSTableRowView
  - ObjC.AppKit.NSTableView
  - ObjC.AppKit.NSTableViewDiffableDataSource
  - ObjC.AppKit.NSTableViewRowAction
  - ObjC.AppKit.NSText
  - ObjC.AppKit.NSTextAlternatives
  - ObjC.AppKit.NSTextAttachment
  - ObjC.AppKit.NSTextAttachmentCell
  - ObjC.AppKit.NSTextAttachmentViewProvider
  - ObjC.AppKit.NSTextBlock
  - ObjC.AppKit.NSTextCheckingController
  - ObjC.AppKit.NSTextContainer
  - ObjC.AppKit.NSTextContentManager
  - ObjC.AppKit.NSTextContentStorage
  - ObjC.AppKit.NSTextElement
  - ObjC.AppKit.NSTextField
  - ObjC.AppKit.NSTextFieldCell
  - ObjC.AppKit.NSTextFinder
  - ObjC.AppKit.NSTextInputContext
  - ObjC.AppKit.NSTextInsertionIndicator
  - ObjC.AppKit.NSTextLayoutFragment
  - ObjC.AppKit.NSTextLayoutManager
  - ObjC.AppKit.NSTextLineFragment
  - ObjC.AppKit.NSTextList
  - ObjC.AppKit.NSTextListElement
  - ObjC.AppKit.NSTextParagraph
  - ObjC.AppKit.NSTextPreview
  - ObjC.AppKit.NSTextRange
  - ObjC.AppKit.NSTextSelection
  - ObjC.AppKit.NSTextSelectionNavigation
  - ObjC.AppKit.NSTextStorage
  - ObjC.AppKit.NSTextTab
  - ObjC.AppKit.NSTextTable
  - ObjC.AppKit.NSTextTableBlock
  - ObjC.AppKit.NSTextView
  - ObjC.AppKit.NSTextViewportLayoutController
  - ObjC.AppKit.NSTintConfiguration
  - ObjC.AppKit.NSTitlebarAccessoryViewController
  - ObjC.AppKit.NSTokenField
  - ObjC.AppKit.NSTokenFieldCell
  - ObjC.AppKit.NSToolbar
  - ObjC.AppKit.NSToolbarItem
  - ObjC.AppKit.NSToolbarItemGroup
  - ObjC.AppKit.NSTouch
  - ObjC.AppKit.NSTouchBar
  - ObjC.AppKit.NSTouchBarItem
  - ObjC.AppKit.NSTrackingArea
  - ObjC.AppKit.NSTrackingSeparatorToolbarItem
  - ObjC.AppKit.NSTreeController
  - ObjC.AppKit.NSTreeNode
  - ObjC.AppKit.NSTypesetter
  - ObjC.AppKit.NSUserDefaultsController
  - ObjC.AppKit.NSUserInterfaceCompressionOptions
  - ObjC.AppKit.NSView
  - ObjC.AppKit.NSViewAnimation
  - ObjC.AppKit.NSViewController
  - ObjC.AppKit.NSViewLayoutRegion
  - ObjC.AppKit.NSVisualEffectView
  - ObjC.AppKit.NSWindow
  - ObjC.AppKit.NSWindowController
  - ObjC.AppKit.NSWindowTab
  - ObjC.AppKit.NSWindowTabGroup
  - ObjC.AppKit.NSWorkspace
  - ObjC.AppKit.NSWorkspaceAuthorization
  - ObjC.AppKit.NSWorkspaceOpenConfiguration
  - ObjC.AppKit.NSWritingToolsCoordinator
  - ObjC.AppKit.NSWritingToolsCoordinatorAnimationParameters
  - ObjC.AppKit.NSWritingToolsCoordinatorContext
  - ObjC.AppKit.Structs
