name:                objc-fileproviderui
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the FileProviderUI framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.FileProviderUI.Enums
  - ObjC.FileProviderUI.FPUIActionExtensionContext
  - ObjC.FileProviderUI.FPUIActionExtensionViewController
  - ObjC.FileProviderUI.Internal.Classes
  - ObjC.FileProviderUI.Internal.Enums
