name:                apple-coremotion-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CoreMotion framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CoreMotion.CMAbsoluteAltitudeData
  - ObjC.CoreMotion.CMAccelerometerData
  - ObjC.CoreMotion.CMAltimeter
  - ObjC.CoreMotion.CMAltitudeData
  - ObjC.CoreMotion.CMAmbientPressureData
  - ObjC.CoreMotion.CMAttitude
  - ObjC.CoreMotion.CMBatchedSensorManager
  - ObjC.CoreMotion.CMDeviceMotion
  - ObjC.CoreMotion.CMDyskineticSymptomResult
  - ObjC.CoreMotion.CMFallDetectionEvent
  - ObjC.CoreMotion.CMFallDetectionManager
  - ObjC.CoreMotion.CMGyroData
  - ObjC.CoreMotion.CMHeadphoneActivityManager
  - ObjC.CoreMotion.CMHeadphoneMotionManager
  - ObjC.CoreMotion.CMHighFrequencyHeartRateData
  - ObjC.CoreMotion.CMLogItem
  - ObjC.CoreMotion.CMMagnetometerData
  - ObjC.CoreMotion.CMMotionActivity
  - ObjC.CoreMotion.CMMotionActivityManager
  - ObjC.CoreMotion.CMMotionManager
  - ObjC.CoreMotion.CMMovementDisorderManager
  - ObjC.CoreMotion.CMOdometerData
  - ObjC.CoreMotion.CMPedometer
  - ObjC.CoreMotion.CMPedometerData
  - ObjC.CoreMotion.CMPedometerEvent
  - ObjC.CoreMotion.CMRecordedAccelerometerData
  - ObjC.CoreMotion.CMRecordedPressureData
  - ObjC.CoreMotion.CMRecordedRotationRateData
  - ObjC.CoreMotion.CMRotationRateData
  - ObjC.CoreMotion.CMSensorDataList
  - ObjC.CoreMotion.CMSensorRecorder
  - ObjC.CoreMotion.CMStepCounter
  - ObjC.CoreMotion.CMTremorResult
  - ObjC.CoreMotion.CMWaterSubmersionEvent
  - ObjC.CoreMotion.CMWaterSubmersionManager
  - ObjC.CoreMotion.CMWaterSubmersionMeasurement
  - ObjC.CoreMotion.CMWaterTemperature
  - ObjC.CoreMotion.Delegate.CMFallDetectionDelegate
  - ObjC.CoreMotion.Delegate.CMHeadphoneMotionManagerDelegate
  - ObjC.CoreMotion.Delegate.CMWaterSubmersionManagerDelegate
  - ObjC.CoreMotion.Enums
  - ObjC.CoreMotion.Internal.Classes
  - ObjC.CoreMotion.Internal.Enums
