name:                objc-security
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Security framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Security
  - ObjC.Security.Enums
  - ObjC.Security.Internal.Enums
  - ObjC.Security.Internal.Structs
  - ObjC.Security.Structs
