name:                apple-addressbook-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AddressBook framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AddressBook.ABAddressBook
  - ObjC.AddressBook.ABGroup
  - ObjC.AddressBook.ABMultiValue
  - ObjC.AddressBook.ABMutableMultiValue
  - ObjC.AddressBook.ABPerson
  - ObjC.AddressBook.ABRecord
  - ObjC.AddressBook.ABSearchElement
  - ObjC.AddressBook.Delegate.ABImageClient
  - ObjC.AddressBook.Internal.Classes
