name:                objc-javascriptcore
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the JavaScriptCore framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.JavaScriptCore.Enums
  - ObjC.JavaScriptCore.Internal.Classes
  - ObjC.JavaScriptCore.Internal.Enums
  - ObjC.JavaScriptCore.JSContext
  - ObjC.JavaScriptCore.JSManagedValue
  - ObjC.JavaScriptCore.JSValue
  - ObjC.JavaScriptCore.JSVirtualMachine
