name:                objc-identitylookup
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the IdentityLookup framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.IdentityLookup.Enums
  - ObjC.IdentityLookup.ILCallClassificationRequest
  - ObjC.IdentityLookup.ILCallCommunication
  - ObjC.IdentityLookup.ILClassificationRequest
  - ObjC.IdentityLookup.ILClassificationResponse
  - ObjC.IdentityLookup.ILCommunication
  - ObjC.IdentityLookup.ILMessageClassificationRequest
  - ObjC.IdentityLookup.ILMessageCommunication
  - ObjC.IdentityLookup.ILMessageFilterCapabilitiesQueryRequest
  - ObjC.IdentityLookup.ILMessageFilterCapabilitiesQueryResponse
  - ObjC.IdentityLookup.ILMessageFilterExtension
  - ObjC.IdentityLookup.ILMessageFilterExtensionContext
  - ObjC.IdentityLookup.ILMessageFilterQueryRequest
  - ObjC.IdentityLookup.ILMessageFilterQueryResponse
  - ObjC.IdentityLookup.ILNetworkResponse
  - ObjC.IdentityLookup.Internal.Classes
  - ObjC.IdentityLookup.Internal.Enums
