name:                objc-avkit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AVKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-avfoundation
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AVKit.AVCaptureView
  - ObjC.AVKit.AVPictureInPictureController
  - ObjC.AVKit.AVPictureInPictureControllerContentSource
  - ObjC.AVKit.AVPlaybackSpeed
  - ObjC.AVKit.AVPlayerView
  - ObjC.AVKit.AVRoutePickerView
  - ObjC.AVKit.Enums
  - ObjC.AVKit.Internal.Classes
  - ObjC.AVKit.Internal.Enums
