name:                apple-browserenginekit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the BrowserEngineKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-avfoundation-gen
- apple-foundation-gen
- apple-uniformtypeidentifiers-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.BrowserEngineKit.BEAccessibilityTextMarker
  - ObjC.BrowserEngineKit.BEAccessibilityTextMarkerRange
  - ObjC.BrowserEngineKit.BEDownloadMonitor
  - ObjC.BrowserEngineKit.BEDownloadMonitorLocation
  - ObjC.BrowserEngineKit.BELayerHierarchy
  - ObjC.BrowserEngineKit.BELayerHierarchyHandle
  - ObjC.BrowserEngineKit.BELayerHierarchyHostingTransactionCoordinator
  - ObjC.BrowserEngineKit.BEMediaEnvironment
  - ObjC.BrowserEngineKit.BENetworkingProcess
  - ObjC.BrowserEngineKit.BEProcessCapability
  - ObjC.BrowserEngineKit.BERenderingProcess
  - ObjC.BrowserEngineKit.BETextAlternatives
  - ObjC.BrowserEngineKit.BETextSuggestion
  - ObjC.BrowserEngineKit.BEWebAppManifest
  - ObjC.BrowserEngineKit.BEWebContentFilter
  - ObjC.BrowserEngineKit.BEWebContentProcess
  - ObjC.BrowserEngineKit.Delegate.BEAccessibilityTextMarkerSupport
  - ObjC.BrowserEngineKit.Delegate.BEExtensionProcess
  - ObjC.BrowserEngineKit.Delegate.BEProcessCapabilityGrant
  - ObjC.BrowserEngineKit.Delegate.BETextInputDelegate
  - ObjC.BrowserEngineKit.Delegate.BETextInteractionDelegate
  - ObjC.BrowserEngineKit.Enums
  - ObjC.BrowserEngineKit.Internal.Classes
  - ObjC.BrowserEngineKit.Internal.Enums
