name:                objc-coreservices
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CoreServices framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-corefoundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CoreServices
  - ObjC.CoreServices.Enums
  - ObjC.CoreServices.Internal.Enums
  - ObjC.CoreServices.Internal.Structs
  - ObjC.CoreServices.Structs
