name:                objc-avfoundation
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the AVFoundation framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-coreimage
- objc-foundation
- objc-mediaplayer
- objc-quartzcore
- objc-uniformtypeidentifiers

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.AVFoundation.AVAggregateAssetDownloadTask
  - ObjC.AVFoundation.AVAsset
  - ObjC.AVFoundation.AVAssetCache
  - ObjC.AVFoundation.AVAssetDownloadConfiguration
  - ObjC.AVFoundation.AVAssetDownloadContentConfiguration
  - ObjC.AVFoundation.AVAssetDownloadStorageManagementPolicy
  - ObjC.AVFoundation.AVAssetDownloadStorageManager
  - ObjC.AVFoundation.AVAssetDownloadTask
  - ObjC.AVFoundation.AVAssetDownloadURLSession
  - ObjC.AVFoundation.AVAssetExportSession
  - ObjC.AVFoundation.AVAssetImageGenerator
  - ObjC.AVFoundation.AVAssetPlaybackAssistant
  - ObjC.AVFoundation.AVAssetReader
  - ObjC.AVFoundation.AVAssetReaderAudioMixOutput
  - ObjC.AVFoundation.AVAssetReaderOutput
  - ObjC.AVFoundation.AVAssetReaderOutputCaptionAdaptor
  - ObjC.AVFoundation.AVAssetReaderOutputMetadataAdaptor
  - ObjC.AVFoundation.AVAssetReaderSampleReferenceOutput
  - ObjC.AVFoundation.AVAssetReaderTrackOutput
  - ObjC.AVFoundation.AVAssetReaderVideoCompositionOutput
  - ObjC.AVFoundation.AVAssetResourceLoader
  - ObjC.AVFoundation.AVAssetResourceLoadingContentInformationRequest
  - ObjC.AVFoundation.AVAssetResourceLoadingContentInformationRequestInternal
  - ObjC.AVFoundation.AVAssetResourceLoadingDataRequest
  - ObjC.AVFoundation.AVAssetResourceLoadingDataRequestInternal
  - ObjC.AVFoundation.AVAssetResourceLoadingRequest
  - ObjC.AVFoundation.AVAssetResourceLoadingRequestInternal
  - ObjC.AVFoundation.AVAssetResourceLoadingRequestor
  - ObjC.AVFoundation.AVAssetResourceRenewalRequest
  - ObjC.AVFoundation.AVAssetSegmentReport
  - ObjC.AVFoundation.AVAssetSegmentReportSampleInformation
  - ObjC.AVFoundation.AVAssetSegmentTrackReport
  - ObjC.AVFoundation.AVAssetTrack
  - ObjC.AVFoundation.AVAssetTrackGroup
  - ObjC.AVFoundation.AVAssetTrackSegment
  - ObjC.AVFoundation.AVAssetVariant
  - ObjC.AVFoundation.AVAssetVariantAudioAttributes
  - ObjC.AVFoundation.AVAssetVariantAudioRenditionSpecificAttributes
  - ObjC.AVFoundation.AVAssetVariantQualifier
  - ObjC.AVFoundation.AVAssetVariantVideoAttributes
  - ObjC.AVFoundation.AVAssetVariantVideoLayoutAttributes
  - ObjC.AVFoundation.AVAssetWriter
  - ObjC.AVFoundation.AVAssetWriterInput
  - ObjC.AVFoundation.AVAssetWriterInputCaptionAdaptor
  - ObjC.AVFoundation.AVAssetWriterInputGroup
  - ObjC.AVFoundation.AVAssetWriterInputMetadataAdaptor
  - ObjC.AVFoundation.AVAssetWriterInputPassDescription
  - ObjC.AVFoundation.AVAssetWriterInputPixelBufferAdaptor
  - ObjC.AVFoundation.AVAssetWriterInputTaggedPixelBufferGroupAdaptor
  - ObjC.AVFoundation.AVAsynchronousCIImageFilteringRequest
  - ObjC.AVFoundation.AVAsynchronousVideoCompositionRequest
  - ObjC.AVFoundation.AVAudioMix
  - ObjC.AVFoundation.AVAudioMixInputParameters
  - ObjC.AVFoundation.AVAudioMixInputParametersInternal
  - ObjC.AVFoundation.AVAudioMixInternal
  - ObjC.AVFoundation.AVCameraCalibrationData
  - ObjC.AVFoundation.AVCaption
  - ObjC.AVFoundation.AVCaptionConversionAdjustment
  - ObjC.AVFoundation.AVCaptionConversionTimeRangeAdjustment
  - ObjC.AVFoundation.AVCaptionConversionValidator
  - ObjC.AVFoundation.AVCaptionConversionWarning
  - ObjC.AVFoundation.AVCaptionFormatConformer
  - ObjC.AVFoundation.AVCaptionGroup
  - ObjC.AVFoundation.AVCaptionGrouper
  - ObjC.AVFoundation.AVCaptionRegion
  - ObjC.AVFoundation.AVCaptionRenderer
  - ObjC.AVFoundation.AVCaptionRendererScene
  - ObjC.AVFoundation.AVCaptionRuby
  - ObjC.AVFoundation.AVCaptureAudioChannel
  - ObjC.AVFoundation.AVCaptureAudioDataOutput
  - ObjC.AVFoundation.AVCaptureAudioFileOutput
  - ObjC.AVFoundation.AVCaptureAudioPreviewOutput
  - ObjC.AVFoundation.AVCaptureAutoExposureBracketedStillImageSettings
  - ObjC.AVFoundation.AVCaptureBracketedStillImageSettings
  - ObjC.AVFoundation.AVCaptureConnection
  - ObjC.AVFoundation.AVCaptureControl
  - ObjC.AVFoundation.AVCaptureDataOutputSynchronizer
  - ObjC.AVFoundation.AVCaptureDeferredPhotoProxy
  - ObjC.AVFoundation.AVCaptureDepthDataOutput
  - ObjC.AVFoundation.AVCaptureDeskViewApplication
  - ObjC.AVFoundation.AVCaptureDeskViewApplicationLaunchConfiguration
  - ObjC.AVFoundation.AVCaptureDevice
  - ObjC.AVFoundation.AVCaptureDeviceDiscoverySession
  - ObjC.AVFoundation.AVCaptureDeviceFormat
  - ObjC.AVFoundation.AVCaptureDeviceInput
  - ObjC.AVFoundation.AVCaptureDeviceInputSource
  - ObjC.AVFoundation.AVCaptureDeviceRotationCoordinator
  - ObjC.AVFoundation.AVCaptureExternalDisplayConfiguration
  - ObjC.AVFoundation.AVCaptureExternalDisplayConfigurator
  - ObjC.AVFoundation.AVCaptureFileOutput
  - ObjC.AVFoundation.AVCaptureFraming
  - ObjC.AVFoundation.AVCaptureIndexPicker
  - ObjC.AVFoundation.AVCaptureInput
  - ObjC.AVFoundation.AVCaptureInputPort
  - ObjC.AVFoundation.AVCaptureManualExposureBracketedStillImageSettings
  - ObjC.AVFoundation.AVCaptureMetadataInput
  - ObjC.AVFoundation.AVCaptureMetadataOutput
  - ObjC.AVFoundation.AVCaptureMovieFileOutput
  - ObjC.AVFoundation.AVCaptureMultiCamSession
  - ObjC.AVFoundation.AVCaptureOutput
  - ObjC.AVFoundation.AVCapturePhoto
  - ObjC.AVFoundation.AVCapturePhotoBracketSettings
  - ObjC.AVFoundation.AVCapturePhotoOutput
  - ObjC.AVFoundation.AVCapturePhotoOutputReadinessCoordinator
  - ObjC.AVFoundation.AVCapturePhotoSettings
  - ObjC.AVFoundation.AVCaptureReactionEffectState
  - ObjC.AVFoundation.AVCaptureResolvedPhotoSettings
  - ObjC.AVFoundation.AVCaptureScreenInput
  - ObjC.AVFoundation.AVCaptureSession
  - ObjC.AVFoundation.AVCaptureSlider
  - ObjC.AVFoundation.AVCaptureSmartFramingMonitor
  - ObjC.AVFoundation.AVCaptureSpatialAudioMetadataSampleGenerator
  - ObjC.AVFoundation.AVCaptureStillImageOutput
  - ObjC.AVFoundation.AVCaptureSynchronizedData
  - ObjC.AVFoundation.AVCaptureSynchronizedDataCollection
  - ObjC.AVFoundation.AVCaptureSynchronizedDepthData
  - ObjC.AVFoundation.AVCaptureSynchronizedMetadataObjectData
  - ObjC.AVFoundation.AVCaptureSynchronizedSampleBufferData
  - ObjC.AVFoundation.AVCaptureSystemExposureBiasSlider
  - ObjC.AVFoundation.AVCaptureSystemPressureState
  - ObjC.AVFoundation.AVCaptureSystemZoomSlider
  - ObjC.AVFoundation.AVCaptureTimecodeGenerator
  - ObjC.AVFoundation.AVCaptureTimecodeSource
  - ObjC.AVFoundation.AVCaptureVideoDataOutput
  - ObjC.AVFoundation.AVCaptureVideoPreviewLayer
  - ObjC.AVFoundation.AVComposition
  - ObjC.AVFoundation.AVCompositionTrack
  - ObjC.AVFoundation.AVCompositionTrackFormatDescriptionReplacement
  - ObjC.AVFoundation.AVCompositionTrackInternal
  - ObjC.AVFoundation.AVCompositionTrackSegment
  - ObjC.AVFoundation.AVCompositionTrackSegmentInternal
  - ObjC.AVFoundation.AVContentKey
  - ObjC.AVFoundation.AVContentKeyRequest
  - ObjC.AVFoundation.AVContentKeyResponse
  - ObjC.AVFoundation.AVContentKeySession
  - ObjC.AVFoundation.AVContentKeySpecifier
  - ObjC.AVFoundation.AVContinuityDevice
  - ObjC.AVFoundation.AVCoordinatedPlaybackParticipant
  - ObjC.AVFoundation.AVCoordinatedPlaybackSuspension
  - ObjC.AVFoundation.AVCustomMediaSelectionScheme
  - ObjC.AVFoundation.AVDateRangeMetadataGroup
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinator
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinatorBufferingCommand
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinatorPauseCommand
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinatorPlayCommand
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinatorPlaybackControlCommand
  - ObjC.AVFoundation.AVDelegatingPlaybackCoordinatorSeekCommand
  - ObjC.AVFoundation.AVDepthData
  - ObjC.AVFoundation.AVExposureBiasRange
  - ObjC.AVFoundation.AVExternalStorageDevice
  - ObjC.AVFoundation.AVExternalStorageDeviceDiscoverySession
  - ObjC.AVFoundation.AVExternalSyncDevice
  - ObjC.AVFoundation.AVExternalSyncDeviceDiscoverySession
  - ObjC.AVFoundation.AVFragmentedAsset
  - ObjC.AVFoundation.AVFragmentedAssetMinder
  - ObjC.AVFoundation.AVFragmentedAssetTrack
  - ObjC.AVFoundation.AVFragmentedMovie
  - ObjC.AVFoundation.AVFragmentedMovieMinder
  - ObjC.AVFoundation.AVFragmentedMovieTrack
  - ObjC.AVFoundation.AVFrameRateRange
  - ObjC.AVFoundation.AVMediaDataStorage
  - ObjC.AVFoundation.AVMediaExtensionProperties
  - ObjC.AVFoundation.AVMediaPresentationSelector
  - ObjC.AVFoundation.AVMediaPresentationSetting
  - ObjC.AVFoundation.AVMediaSelection
  - ObjC.AVFoundation.AVMediaSelectionGroup
  - ObjC.AVFoundation.AVMediaSelectionOption
  - ObjC.AVFoundation.AVMetadataBodyObject
  - ObjC.AVFoundation.AVMetadataCatBodyObject
  - ObjC.AVFoundation.AVMetadataCatHeadObject
  - ObjC.AVFoundation.AVMetadataDogBodyObject
  - ObjC.AVFoundation.AVMetadataDogHeadObject
  - ObjC.AVFoundation.AVMetadataFaceObject
  - ObjC.AVFoundation.AVMetadataGroup
  - ObjC.AVFoundation.AVMetadataHumanBodyObject
  - ObjC.AVFoundation.AVMetadataHumanFullBodyObject
  - ObjC.AVFoundation.AVMetadataItem
  - ObjC.AVFoundation.AVMetadataItemFilter
  - ObjC.AVFoundation.AVMetadataItemFilterInternal
  - ObjC.AVFoundation.AVMetadataItemInternal
  - ObjC.AVFoundation.AVMetadataItemValueRequest
  - ObjC.AVFoundation.AVMetadataMachineReadableCodeObject
  - ObjC.AVFoundation.AVMetadataObject
  - ObjC.AVFoundation.AVMetadataSalientObject
  - ObjC.AVFoundation.AVMetricContentKeyRequestEvent
  - ObjC.AVFoundation.AVMetricDownloadSummaryEvent
  - ObjC.AVFoundation.AVMetricErrorEvent
  - ObjC.AVFoundation.AVMetricEvent
  - ObjC.AVFoundation.AVMetricEventStream
  - ObjC.AVFoundation.AVMetricHLSMediaSegmentRequestEvent
  - ObjC.AVFoundation.AVMetricHLSPlaylistRequestEvent
  - ObjC.AVFoundation.AVMetricMediaRendition
  - ObjC.AVFoundation.AVMetricMediaResourceRequestEvent
  - ObjC.AVFoundation.AVMetricPlayerItemInitialLikelyToKeepUpEvent
  - ObjC.AVFoundation.AVMetricPlayerItemLikelyToKeepUpEvent
  - ObjC.AVFoundation.AVMetricPlayerItemPlaybackSummaryEvent
  - ObjC.AVFoundation.AVMetricPlayerItemRateChangeEvent
  - ObjC.AVFoundation.AVMetricPlayerItemSeekDidCompleteEvent
  - ObjC.AVFoundation.AVMetricPlayerItemSeekEvent
  - ObjC.AVFoundation.AVMetricPlayerItemStallEvent
  - ObjC.AVFoundation.AVMetricPlayerItemVariantSwitchEvent
  - ObjC.AVFoundation.AVMetricPlayerItemVariantSwitchStartEvent
  - ObjC.AVFoundation.AVMovie
  - ObjC.AVFoundation.AVMovieTrack
  - ObjC.AVFoundation.AVMovieTrackInternal
  - ObjC.AVFoundation.AVMutableAssetDownloadStorageManagementPolicy
  - ObjC.AVFoundation.AVMutableAudioMix
  - ObjC.AVFoundation.AVMutableAudioMixInputParameters
  - ObjC.AVFoundation.AVMutableCaption
  - ObjC.AVFoundation.AVMutableCaptionRegion
  - ObjC.AVFoundation.AVMutableComposition
  - ObjC.AVFoundation.AVMutableCompositionTrack
  - ObjC.AVFoundation.AVMutableCompositionTrackInternal
  - ObjC.AVFoundation.AVMutableDateRangeMetadataGroup
  - ObjC.AVFoundation.AVMutableMediaSelection
  - ObjC.AVFoundation.AVMutableMetadataItem
  - ObjC.AVFoundation.AVMutableMetadataItemInternal
  - ObjC.AVFoundation.AVMutableMovie
  - ObjC.AVFoundation.AVMutableMovieTrack
  - ObjC.AVFoundation.AVMutableMovieTrackInternal
  - ObjC.AVFoundation.AVMutableTimedMetadataGroup
  - ObjC.AVFoundation.AVMutableVideoComposition
  - ObjC.AVFoundation.AVMutableVideoCompositionInstruction
  - ObjC.AVFoundation.AVMutableVideoCompositionLayerInstruction
  - ObjC.AVFoundation.AVOutputSettingsAssistant
  - ObjC.AVFoundation.AVPersistableContentKeyRequest
  - ObjC.AVFoundation.AVPlaybackCoordinationMedium
  - ObjC.AVFoundation.AVPlaybackCoordinator
  - ObjC.AVFoundation.AVPlayer
  - ObjC.AVFoundation.AVPlayerInterstitialEvent
  - ObjC.AVFoundation.AVPlayerInterstitialEventController
  - ObjC.AVFoundation.AVPlayerInterstitialEventMonitor
  - ObjC.AVFoundation.AVPlayerItem
  - ObjC.AVFoundation.AVPlayerItemAccessLog
  - ObjC.AVFoundation.AVPlayerItemAccessLogEvent
  - ObjC.AVFoundation.AVPlayerItemErrorLog
  - ObjC.AVFoundation.AVPlayerItemErrorLogEvent
  - ObjC.AVFoundation.AVPlayerItemIntegratedTimeline
  - ObjC.AVFoundation.AVPlayerItemIntegratedTimelineSnapshot
  - ObjC.AVFoundation.AVPlayerItemLegibleOutput
  - ObjC.AVFoundation.AVPlayerItemMediaDataCollector
  - ObjC.AVFoundation.AVPlayerItemMetadataCollector
  - ObjC.AVFoundation.AVPlayerItemMetadataOutput
  - ObjC.AVFoundation.AVPlayerItemOutput
  - ObjC.AVFoundation.AVPlayerItemOutputInternal
  - ObjC.AVFoundation.AVPlayerItemRenderedLegibleOutput
  - ObjC.AVFoundation.AVPlayerItemSegment
  - ObjC.AVFoundation.AVPlayerItemTrack
  - ObjC.AVFoundation.AVPlayerItemVideoOutput
  - ObjC.AVFoundation.AVPlayerLayer
  - ObjC.AVFoundation.AVPlayerLooper
  - ObjC.AVFoundation.AVPlayerMediaSelectionCriteria
  - ObjC.AVFoundation.AVPlayerPlaybackCoordinator
  - ObjC.AVFoundation.AVPlayerVideoOutput
  - ObjC.AVFoundation.AVPlayerVideoOutputConfiguration
  - ObjC.AVFoundation.AVPortraitEffectsMatte
  - ObjC.AVFoundation.AVQueuePlayer
  - ObjC.AVFoundation.AVRenderedCaptionImage
  - ObjC.AVFoundation.AVRouteDetector
  - ObjC.AVFoundation.AVSampleBufferAudioRenderer
  - ObjC.AVFoundation.AVSampleBufferDisplayLayer
  - ObjC.AVFoundation.AVSampleBufferGenerator
  - ObjC.AVFoundation.AVSampleBufferGeneratorBatch
  - ObjC.AVFoundation.AVSampleBufferRenderSynchronizer
  - ObjC.AVFoundation.AVSampleBufferRequest
  - ObjC.AVFoundation.AVSampleBufferVideoRenderer
  - ObjC.AVFoundation.AVSampleCursor
  - ObjC.AVFoundation.AVSampleCursorInternal
  - ObjC.AVFoundation.AVSemanticSegmentationMatte
  - ObjC.AVFoundation.AVSpatialVideoConfiguration
  - ObjC.AVFoundation.AVSynchronizedLayer
  - ObjC.AVFoundation.AVTextStyleRule
  - ObjC.AVFoundation.AVTextStyleRuleInternal
  - ObjC.AVFoundation.AVTimedMetadataGroup
  - ObjC.AVFoundation.AVURLAsset
  - ObjC.AVFoundation.AVVideoComposition
  - ObjC.AVFoundation.AVVideoCompositionCoreAnimationTool
  - ObjC.AVFoundation.AVVideoCompositionInstruction
  - ObjC.AVFoundation.AVVideoCompositionLayerInstruction
  - ObjC.AVFoundation.AVVideoCompositionRenderContext
  - ObjC.AVFoundation.AVVideoCompositionRenderHint
  - ObjC.AVFoundation.AVVideoOutputSpecification
  - ObjC.AVFoundation.AVVideoPerformanceMetrics
  - ObjC.AVFoundation.AVZoomRange
  - ObjC.AVFoundation.Enums
  - ObjC.AVFoundation.Internal.Classes
  - ObjC.AVFoundation.Internal.Enums
  - ObjC.AVFoundation.Internal.Structs
  - ObjC.AVFoundation.NSCoder
  - ObjC.AVFoundation.NSValue
  - ObjC.AVFoundation.Structs
