name:                apple-sharedwithyoucore-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SharedWithYouCore framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SharedWithYouCore.Delegate.SWCollaborationActionHandler
  - ObjC.SharedWithYouCore.Internal.Classes
  - ObjC.SharedWithYouCore.SWAction
  - ObjC.SharedWithYouCore.SWCollaborationCoordinator
  - ObjC.SharedWithYouCore.SWCollaborationMetadata
  - ObjC.SharedWithYouCore.SWCollaborationOption
  - ObjC.SharedWithYouCore.SWCollaborationOptionsGroup
  - ObjC.SharedWithYouCore.SWCollaborationOptionsPickerGroup
  - ObjC.SharedWithYouCore.SWCollaborationShareOptions
  - ObjC.SharedWithYouCore.SWPerson
  - ObjC.SharedWithYouCore.SWPersonIdentity
  - ObjC.SharedWithYouCore.SWPersonIdentityProof
  - ObjC.SharedWithYouCore.SWSignedPersonIdentityProof
  - ObjC.SharedWithYouCore.SWStartCollaborationAction
  - ObjC.SharedWithYouCore.SWUpdateCollaborationParticipantsAction
