name:                objc-installerplugins
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the InstallerPlugins framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.InstallerPlugins.Enums
  - ObjC.InstallerPlugins.InstallerPane
  - ObjC.InstallerPlugins.InstallerSection
  - ObjC.InstallerPlugins.InstallerState
  - ObjC.InstallerPlugins.Internal.Classes
  - ObjC.InstallerPlugins.Internal.Enums
