name:                apple-fskit-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the FSKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.FSKit.Delegate.FSFileSystemBase
  - ObjC.FSKit.Delegate.FSManageableResourceMaintenanceOperations
  - ObjC.FSKit.Delegate.FSUnaryFileSystemOperations
  - ObjC.FSKit.Delegate.FSVolumeAccessCheckOperations
  - ObjC.FSKit.Delegate.FSVolumeOpenCloseOperations
  - ObjC.FSKit.Delegate.FSVolumeOperations
  - ObjC.FSKit.Delegate.FSVolumePathConfOperations
  - ObjC.FSKit.Delegate.FSVolumePreallocateOperations
  - ObjC.FSKit.Delegate.FSVolumeRenameOperations
  - ObjC.FSKit.Delegate.FSVolumeXattrOperations
  - ObjC.FSKit.Enums
  - ObjC.FSKit.FSBlockDeviceResource
  - ObjC.FSKit.FSClient
  - ObjC.FSKit.FSContainerIdentifier
  - ObjC.FSKit.FSContainerStatus
  - ObjC.FSKit.FSDirectoryEntryPacker
  - ObjC.FSKit.FSEntityIdentifier
  - ObjC.FSKit.FSExtentPacker
  - ObjC.FSKit.FSFileName
  - ObjC.FSKit.FSFileSystem
  - ObjC.FSKit.FSGenericURLResource
  - ObjC.FSKit.FSItem
  - ObjC.FSKit.FSItemAttributes
  - ObjC.FSKit.FSItemGetAttributesRequest
  - ObjC.FSKit.FSItemSetAttributesRequest
  - ObjC.FSKit.FSMetadataRange
  - ObjC.FSKit.FSModuleIdentity
  - ObjC.FSKit.FSMutableFileDataBuffer
  - ObjC.FSKit.FSPathURLResource
  - ObjC.FSKit.FSProbeResult
  - ObjC.FSKit.FSResource
  - ObjC.FSKit.FSStatFSResult
  - ObjC.FSKit.FSTask
  - ObjC.FSKit.FSTaskOptions
  - ObjC.FSKit.FSUnaryFileSystem
  - ObjC.FSKit.FSVolume
  - ObjC.FSKit.FSVolumeIdentifier
  - ObjC.FSKit.FSVolumeSupportedCapabilities
  - ObjC.FSKit.Internal.Classes
  - ObjC.FSKit.Internal.Enums
