name:                objc-iokit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the IOKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.IOKit
  - ObjC.IOKit.Enums
  - ObjC.IOKit.Internal.Enums
  - ObjC.IOKit.Internal.Structs
  - ObjC.IOKit.Structs
