name:                apple-systemextensions-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SystemExtensions framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SystemExtensions.Delegate.OSSystemExtensionRequestDelegate
  - ObjC.SystemExtensions.Delegate.OSSystemExtensionsWorkspaceObserver
  - ObjC.SystemExtensions.Enums
  - ObjC.SystemExtensions.Internal.Classes
  - ObjC.SystemExtensions.Internal.Enums
  - ObjC.SystemExtensions.OSSystemExtensionInfo
  - ObjC.SystemExtensions.OSSystemExtensionManager
  - ObjC.SystemExtensions.OSSystemExtensionProperties
  - ObjC.SystemExtensions.OSSystemExtensionRequest
  - ObjC.SystemExtensions.OSSystemExtensionsWorkspace
