name:                apple-networkextension-gen
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the NetworkExtension framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-accessorysetupkit-gen
- apple-foundation-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.NetworkExtension.Delegate.NEAppPushDelegate
  - ObjC.NetworkExtension.Delegate.NWTCPConnectionAuthenticationDelegate
  - ObjC.NetworkExtension.Enums
  - ObjC.NetworkExtension.Internal.Classes
  - ObjC.NetworkExtension.Internal.Enums
  - ObjC.NetworkExtension.NEAppProxyFlow
  - ObjC.NetworkExtension.NEAppProxyProvider
  - ObjC.NetworkExtension.NEAppProxyProviderManager
  - ObjC.NetworkExtension.NEAppProxyTCPFlow
  - ObjC.NetworkExtension.NEAppProxyUDPFlow
  - ObjC.NetworkExtension.NEAppPushManager
  - ObjC.NetworkExtension.NEAppPushProvider
  - ObjC.NetworkExtension.NEAppRule
  - ObjC.NetworkExtension.NEDNSOverHTTPSSettings
  - ObjC.NetworkExtension.NEDNSOverTLSSettings
  - ObjC.NetworkExtension.NEDNSProxyManager
  - ObjC.NetworkExtension.NEDNSProxyProvider
  - ObjC.NetworkExtension.NEDNSProxyProviderProtocol
  - ObjC.NetworkExtension.NEDNSSettings
  - ObjC.NetworkExtension.NEDNSSettingsManager
  - ObjC.NetworkExtension.NEEthernetTunnelNetworkSettings
  - ObjC.NetworkExtension.NEEthernetTunnelProvider
  - ObjC.NetworkExtension.NEEvaluateConnectionRule
  - ObjC.NetworkExtension.NEFilterBrowserFlow
  - ObjC.NetworkExtension.NEFilterControlProvider
  - ObjC.NetworkExtension.NEFilterControlVerdict
  - ObjC.NetworkExtension.NEFilterDataProvider
  - ObjC.NetworkExtension.NEFilterDataVerdict
  - ObjC.NetworkExtension.NEFilterFlow
  - ObjC.NetworkExtension.NEFilterManager
  - ObjC.NetworkExtension.NEFilterNewFlowVerdict
  - ObjC.NetworkExtension.NEFilterPacketContext
  - ObjC.NetworkExtension.NEFilterPacketProvider
  - ObjC.NetworkExtension.NEFilterPacketSet
  - ObjC.NetworkExtension.NEFilterProvider
  - ObjC.NetworkExtension.NEFilterProviderConfiguration
  - ObjC.NetworkExtension.NEFilterRemediationVerdict
  - ObjC.NetworkExtension.NEFilterReport
  - ObjC.NetworkExtension.NEFilterRule
  - ObjC.NetworkExtension.NEFilterSettings
  - ObjC.NetworkExtension.NEFilterSocketFlow
  - ObjC.NetworkExtension.NEFilterVerdict
  - ObjC.NetworkExtension.NEFlowMetaData
  - ObjC.NetworkExtension.NEHotspotConfiguration
  - ObjC.NetworkExtension.NEHotspotConfigurationManager
  - ObjC.NetworkExtension.NEHotspotEAPSettings
  - ObjC.NetworkExtension.NEHotspotHS20Settings
  - ObjC.NetworkExtension.NEHotspotHelper
  - ObjC.NetworkExtension.NEHotspotHelperCommand
  - ObjC.NetworkExtension.NEHotspotHelperResponse
  - ObjC.NetworkExtension.NEHotspotNetwork
  - ObjC.NetworkExtension.NEIPv4Route
  - ObjC.NetworkExtension.NEIPv4Settings
  - ObjC.NetworkExtension.NEIPv6Route
  - ObjC.NetworkExtension.NEIPv6Settings
  - ObjC.NetworkExtension.NENetworkRule
  - ObjC.NetworkExtension.NEOnDemandRule
  - ObjC.NetworkExtension.NEOnDemandRuleConnect
  - ObjC.NetworkExtension.NEOnDemandRuleDisconnect
  - ObjC.NetworkExtension.NEOnDemandRuleEvaluateConnection
  - ObjC.NetworkExtension.NEOnDemandRuleIgnore
  - ObjC.NetworkExtension.NEPacket
  - ObjC.NetworkExtension.NEPacketTunnelFlow
  - ObjC.NetworkExtension.NEPacketTunnelNetworkSettings
  - ObjC.NetworkExtension.NEPacketTunnelProvider
  - ObjC.NetworkExtension.NEPrivateLTENetwork
  - ObjC.NetworkExtension.NEProvider
  - ObjC.NetworkExtension.NEProxyServer
  - ObjC.NetworkExtension.NEProxySettings
  - ObjC.NetworkExtension.NERelay
  - ObjC.NetworkExtension.NERelayManager
  - ObjC.NetworkExtension.NETransparentProxyManager
  - ObjC.NetworkExtension.NETransparentProxyNetworkSettings
  - ObjC.NetworkExtension.NETransparentProxyProvider
  - ObjC.NetworkExtension.NETunnelNetworkSettings
  - ObjC.NetworkExtension.NETunnelProvider
  - ObjC.NetworkExtension.NETunnelProviderManager
  - ObjC.NetworkExtension.NETunnelProviderProtocol
  - ObjC.NetworkExtension.NETunnelProviderSession
  - ObjC.NetworkExtension.NEURLFilter
  - ObjC.NetworkExtension.NEVPNConnection
  - ObjC.NetworkExtension.NEVPNIKEv2PPKConfiguration
  - ObjC.NetworkExtension.NEVPNIKEv2SecurityAssociationParameters
  - ObjC.NetworkExtension.NEVPNManager
  - ObjC.NetworkExtension.NEVPNProtocol
  - ObjC.NetworkExtension.NEVPNProtocolIKEv2
  - ObjC.NetworkExtension.NEVPNProtocolIPSec
  - ObjC.NetworkExtension.NWBonjourServiceEndpoint
  - ObjC.NetworkExtension.NWEndpoint
  - ObjC.NetworkExtension.NWHostEndpoint
  - ObjC.NetworkExtension.NWPath
  - ObjC.NetworkExtension.NWTCPConnection
  - ObjC.NetworkExtension.NWTLSParameters
  - ObjC.NetworkExtension.NWUDPSession
