name:                objc-intents
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the Intents framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-corelocation
- objc-eventkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.Intents.CLPlacemark
  - ObjC.Intents.Enums
  - ObjC.Intents.INAccountTypeResolutionResult
  - ObjC.Intents.INActivateCarSignalIntent
  - ObjC.Intents.INActivateCarSignalIntentResponse
  - ObjC.Intents.INAddMediaIntent
  - ObjC.Intents.INAddMediaIntentResponse
  - ObjC.Intents.INAddMediaMediaDestinationResolutionResult
  - ObjC.Intents.INAddMediaMediaItemResolutionResult
  - ObjC.Intents.INAddTasksIntent
  - ObjC.Intents.INAddTasksIntentResponse
  - ObjC.Intents.INAddTasksTargetTaskListResolutionResult
  - ObjC.Intents.INAddTasksTemporalEventTriggerResolutionResult
  - ObjC.Intents.INAirline
  - ObjC.Intents.INAirport
  - ObjC.Intents.INAirportGate
  - ObjC.Intents.INAnswerCallIntent
  - ObjC.Intents.INAnswerCallIntentResponse
  - ObjC.Intents.INAppendToNoteIntent
  - ObjC.Intents.INAppendToNoteIntentResponse
  - ObjC.Intents.INBalanceAmount
  - ObjC.Intents.INBalanceTypeResolutionResult
  - ObjC.Intents.INBillDetails
  - ObjC.Intents.INBillPayee
  - ObjC.Intents.INBillPayeeResolutionResult
  - ObjC.Intents.INBillTypeResolutionResult
  - ObjC.Intents.INBoatReservation
  - ObjC.Intents.INBoatTrip
  - ObjC.Intents.INBookRestaurantReservationIntent
  - ObjC.Intents.INBookRestaurantReservationIntentResponse
  - ObjC.Intents.INBooleanResolutionResult
  - ObjC.Intents.INBusReservation
  - ObjC.Intents.INBusTrip
  - ObjC.Intents.INCallCapabilityResolutionResult
  - ObjC.Intents.INCallDestinationTypeResolutionResult
  - ObjC.Intents.INCallGroup
  - ObjC.Intents.INCallRecord
  - ObjC.Intents.INCallRecordFilter
  - ObjC.Intents.INCallRecordResolutionResult
  - ObjC.Intents.INCallRecordTypeOptionsResolutionResult
  - ObjC.Intents.INCallRecordTypeResolutionResult
  - ObjC.Intents.INCancelRideIntent
  - ObjC.Intents.INCancelRideIntentResponse
  - ObjC.Intents.INCancelWorkoutIntent
  - ObjC.Intents.INCancelWorkoutIntentResponse
  - ObjC.Intents.INCar
  - ObjC.Intents.INCarAirCirculationModeResolutionResult
  - ObjC.Intents.INCarAudioSourceResolutionResult
  - ObjC.Intents.INCarDefrosterResolutionResult
  - ObjC.Intents.INCarHeadUnit
  - ObjC.Intents.INCarSeatResolutionResult
  - ObjC.Intents.INCarSignalOptionsResolutionResult
  - ObjC.Intents.INCreateNoteIntent
  - ObjC.Intents.INCreateNoteIntentResponse
  - ObjC.Intents.INCreateTaskListIntent
  - ObjC.Intents.INCreateTaskListIntentResponse
  - ObjC.Intents.INCurrencyAmount
  - ObjC.Intents.INCurrencyAmountResolutionResult
  - ObjC.Intents.INDailyRoutineRelevanceProvider
  - ObjC.Intents.INDateComponentsRange
  - ObjC.Intents.INDateComponentsRangeResolutionResult
  - ObjC.Intents.INDateComponentsResolutionResult
  - ObjC.Intents.INDateRelevanceProvider
  - ObjC.Intents.INDateSearchTypeResolutionResult
  - ObjC.Intents.INDefaultCardTemplate
  - ObjC.Intents.INDeleteTasksIntent
  - ObjC.Intents.INDeleteTasksIntentResponse
  - ObjC.Intents.INDeleteTasksTaskListResolutionResult
  - ObjC.Intents.INDeleteTasksTaskResolutionResult
  - ObjC.Intents.INDoubleResolutionResult
  - ObjC.Intents.INEditMessageIntent
  - ObjC.Intents.INEditMessageIntentResponse
  - ObjC.Intents.INEndWorkoutIntent
  - ObjC.Intents.INEndWorkoutIntentResponse
  - ObjC.Intents.INEnergyResolutionResult
  - ObjC.Intents.INEnumResolutionResult
  - ObjC.Intents.INExtension
  - ObjC.Intents.INFile
  - ObjC.Intents.INFileResolutionResult
  - ObjC.Intents.INFlight
  - ObjC.Intents.INFlightReservation
  - ObjC.Intents.INFocusStatus
  - ObjC.Intents.INFocusStatusCenter
  - ObjC.Intents.INGetAvailableRestaurantReservationBookingDefaultsIntent
  - ObjC.Intents.INGetAvailableRestaurantReservationBookingDefaultsIntentResponse
  - ObjC.Intents.INGetAvailableRestaurantReservationBookingsIntent
  - ObjC.Intents.INGetAvailableRestaurantReservationBookingsIntentResponse
  - ObjC.Intents.INGetCarLockStatusIntent
  - ObjC.Intents.INGetCarLockStatusIntentResponse
  - ObjC.Intents.INGetCarPowerLevelStatusIntent
  - ObjC.Intents.INGetCarPowerLevelStatusIntentResponse
  - ObjC.Intents.INGetReservationDetailsIntent
  - ObjC.Intents.INGetReservationDetailsIntentResponse
  - ObjC.Intents.INGetRestaurantGuestIntent
  - ObjC.Intents.INGetRestaurantGuestIntentResponse
  - ObjC.Intents.INGetRideStatusIntent
  - ObjC.Intents.INGetRideStatusIntentResponse
  - ObjC.Intents.INGetUserCurrentRestaurantReservationBookingsIntent
  - ObjC.Intents.INGetUserCurrentRestaurantReservationBookingsIntentResponse
  - ObjC.Intents.INGetVisualCodeIntent
  - ObjC.Intents.INGetVisualCodeIntentResponse
  - ObjC.Intents.INHangUpCallIntent
  - ObjC.Intents.INHangUpCallIntentResponse
  - ObjC.Intents.INImage
  - ObjC.Intents.INImageNoteContent
  - ObjC.Intents.INIntegerResolutionResult
  - ObjC.Intents.INIntent
  - ObjC.Intents.INIntentDonationMetadata
  - ObjC.Intents.INIntentResolutionResult
  - ObjC.Intents.INIntentResponse
  - ObjC.Intents.INInteraction
  - ObjC.Intents.INLengthResolutionResult
  - ObjC.Intents.INListCarsIntent
  - ObjC.Intents.INListCarsIntentResponse
  - ObjC.Intents.INListRideOptionsIntent
  - ObjC.Intents.INListRideOptionsIntentResponse
  - ObjC.Intents.INLocationRelevanceProvider
  - ObjC.Intents.INLocationSearchTypeResolutionResult
  - ObjC.Intents.INLodgingReservation
  - ObjC.Intents.INMassResolutionResult
  - ObjC.Intents.INMediaAffinityTypeResolutionResult
  - ObjC.Intents.INMediaDestination
  - ObjC.Intents.INMediaDestinationResolutionResult
  - ObjC.Intents.INMediaItem
  - ObjC.Intents.INMediaItemResolutionResult
  - ObjC.Intents.INMediaSearch
  - ObjC.Intents.INMediaUserContext
  - ObjC.Intents.INMessage
  - ObjC.Intents.INMessageAttributeOptionsResolutionResult
  - ObjC.Intents.INMessageAttributeResolutionResult
  - ObjC.Intents.INMessageLinkMetadata
  - ObjC.Intents.INMessageReaction
  - ObjC.Intents.INNote
  - ObjC.Intents.INNoteContent
  - ObjC.Intents.INNoteContentResolutionResult
  - ObjC.Intents.INNoteContentTypeResolutionResult
  - ObjC.Intents.INNoteResolutionResult
  - ObjC.Intents.INNotebookItemTypeResolutionResult
  - ObjC.Intents.INObject
  - ObjC.Intents.INObjectCollection
  - ObjC.Intents.INObjectResolutionResult
  - ObjC.Intents.INObjectSection
  - ObjC.Intents.INOutgoingMessageTypeResolutionResult
  - ObjC.Intents.INParameter
  - ObjC.Intents.INPauseWorkoutIntent
  - ObjC.Intents.INPauseWorkoutIntentResponse
  - ObjC.Intents.INPayBillIntent
  - ObjC.Intents.INPayBillIntentResponse
  - ObjC.Intents.INPaymentAccount
  - ObjC.Intents.INPaymentAccountResolutionResult
  - ObjC.Intents.INPaymentAmount
  - ObjC.Intents.INPaymentAmountResolutionResult
  - ObjC.Intents.INPaymentMethod
  - ObjC.Intents.INPaymentMethodResolutionResult
  - ObjC.Intents.INPaymentRecord
  - ObjC.Intents.INPaymentStatusResolutionResult
  - ObjC.Intents.INPerson
  - ObjC.Intents.INPersonHandle
  - ObjC.Intents.INPersonResolutionResult
  - ObjC.Intents.INPlacemarkResolutionResult
  - ObjC.Intents.INPlayMediaIntent
  - ObjC.Intents.INPlayMediaIntentResponse
  - ObjC.Intents.INPlayMediaMediaItemResolutionResult
  - ObjC.Intents.INPlayMediaPlaybackSpeedResolutionResult
  - ObjC.Intents.INPlaybackQueueLocationResolutionResult
  - ObjC.Intents.INPlaybackRepeatModeResolutionResult
  - ObjC.Intents.INPreferences
  - ObjC.Intents.INPriceRange
  - ObjC.Intents.INRadioTypeResolutionResult
  - ObjC.Intents.INRecurrenceRule
  - ObjC.Intents.INRelativeReferenceResolutionResult
  - ObjC.Intents.INRelativeSettingResolutionResult
  - ObjC.Intents.INRelevanceProvider
  - ObjC.Intents.INRelevantShortcut
  - ObjC.Intents.INRelevantShortcutStore
  - ObjC.Intents.INRentalCar
  - ObjC.Intents.INRentalCarReservation
  - ObjC.Intents.INRequestPaymentCurrencyAmountResolutionResult
  - ObjC.Intents.INRequestPaymentIntent
  - ObjC.Intents.INRequestPaymentIntentResponse
  - ObjC.Intents.INRequestPaymentPayerResolutionResult
  - ObjC.Intents.INRequestRideIntent
  - ObjC.Intents.INRequestRideIntentResponse
  - ObjC.Intents.INReservation
  - ObjC.Intents.INReservationAction
  - ObjC.Intents.INRestaurant
  - ObjC.Intents.INRestaurantGuest
  - ObjC.Intents.INRestaurantGuestDisplayPreferences
  - ObjC.Intents.INRestaurantGuestResolutionResult
  - ObjC.Intents.INRestaurantOffer
  - ObjC.Intents.INRestaurantReservation
  - ObjC.Intents.INRestaurantReservationBooking
  - ObjC.Intents.INRestaurantReservationUserBooking
  - ObjC.Intents.INRestaurantResolutionResult
  - ObjC.Intents.INResumeWorkoutIntent
  - ObjC.Intents.INResumeWorkoutIntentResponse
  - ObjC.Intents.INRideCompletionStatus
  - ObjC.Intents.INRideDriver
  - ObjC.Intents.INRideFareLineItem
  - ObjC.Intents.INRideOption
  - ObjC.Intents.INRidePartySizeOption
  - ObjC.Intents.INRideStatus
  - ObjC.Intents.INRideVehicle
  - ObjC.Intents.INSaveProfileInCarIntent
  - ObjC.Intents.INSaveProfileInCarIntentResponse
  - ObjC.Intents.INSearchCallHistoryIntent
  - ObjC.Intents.INSearchCallHistoryIntentResponse
  - ObjC.Intents.INSearchForAccountsIntent
  - ObjC.Intents.INSearchForAccountsIntentResponse
  - ObjC.Intents.INSearchForBillsIntent
  - ObjC.Intents.INSearchForBillsIntentResponse
  - ObjC.Intents.INSearchForMediaIntent
  - ObjC.Intents.INSearchForMediaIntentResponse
  - ObjC.Intents.INSearchForMediaMediaItemResolutionResult
  - ObjC.Intents.INSearchForMessagesIntent
  - ObjC.Intents.INSearchForMessagesIntentResponse
  - ObjC.Intents.INSearchForNotebookItemsIntent
  - ObjC.Intents.INSearchForNotebookItemsIntentResponse
  - ObjC.Intents.INSearchForPhotosIntent
  - ObjC.Intents.INSearchForPhotosIntentResponse
  - ObjC.Intents.INSeat
  - ObjC.Intents.INSendMessageAttachment
  - ObjC.Intents.INSendMessageIntent
  - ObjC.Intents.INSendMessageIntentDonationMetadata
  - ObjC.Intents.INSendMessageIntentResponse
  - ObjC.Intents.INSendMessageRecipientResolutionResult
  - ObjC.Intents.INSendPaymentCurrencyAmountResolutionResult
  - ObjC.Intents.INSendPaymentIntent
  - ObjC.Intents.INSendPaymentIntentResponse
  - ObjC.Intents.INSendPaymentPayeeResolutionResult
  - ObjC.Intents.INSendRideFeedbackIntent
  - ObjC.Intents.INSendRideFeedbackIntentResponse
  - ObjC.Intents.INSetAudioSourceInCarIntent
  - ObjC.Intents.INSetAudioSourceInCarIntentResponse
  - ObjC.Intents.INSetCarLockStatusIntent
  - ObjC.Intents.INSetCarLockStatusIntentResponse
  - ObjC.Intents.INSetClimateSettingsInCarIntent
  - ObjC.Intents.INSetClimateSettingsInCarIntentResponse
  - ObjC.Intents.INSetDefrosterSettingsInCarIntent
  - ObjC.Intents.INSetDefrosterSettingsInCarIntentResponse
  - ObjC.Intents.INSetMessageAttributeIntent
  - ObjC.Intents.INSetMessageAttributeIntentResponse
  - ObjC.Intents.INSetProfileInCarIntent
  - ObjC.Intents.INSetProfileInCarIntentResponse
  - ObjC.Intents.INSetRadioStationIntent
  - ObjC.Intents.INSetRadioStationIntentResponse
  - ObjC.Intents.INSetSeatSettingsInCarIntent
  - ObjC.Intents.INSetSeatSettingsInCarIntentResponse
  - ObjC.Intents.INSetTaskAttributeIntent
  - ObjC.Intents.INSetTaskAttributeIntentResponse
  - ObjC.Intents.INSetTaskAttributeTemporalEventTriggerResolutionResult
  - ObjC.Intents.INShareFocusStatusIntent
  - ObjC.Intents.INShareFocusStatusIntentResponse
  - ObjC.Intents.INShortcut
  - ObjC.Intents.INSnoozeTasksIntent
  - ObjC.Intents.INSnoozeTasksIntentResponse
  - ObjC.Intents.INSnoozeTasksTaskResolutionResult
  - ObjC.Intents.INSpatialEventTrigger
  - ObjC.Intents.INSpatialEventTriggerResolutionResult
  - ObjC.Intents.INSpeakableString
  - ObjC.Intents.INSpeakableStringResolutionResult
  - ObjC.Intents.INSpeedResolutionResult
  - ObjC.Intents.INStartAudioCallIntent
  - ObjC.Intents.INStartAudioCallIntentResponse
  - ObjC.Intents.INStartCallCallCapabilityResolutionResult
  - ObjC.Intents.INStartCallCallRecordToCallBackResolutionResult
  - ObjC.Intents.INStartCallContactResolutionResult
  - ObjC.Intents.INStartCallIntent
  - ObjC.Intents.INStartCallIntentResponse
  - ObjC.Intents.INStartPhotoPlaybackIntent
  - ObjC.Intents.INStartPhotoPlaybackIntentResponse
  - ObjC.Intents.INStartVideoCallIntent
  - ObjC.Intents.INStartVideoCallIntentResponse
  - ObjC.Intents.INStartWorkoutIntent
  - ObjC.Intents.INStartWorkoutIntentResponse
  - ObjC.Intents.INSticker
  - ObjC.Intents.INStringResolutionResult
  - ObjC.Intents.INTask
  - ObjC.Intents.INTaskList
  - ObjC.Intents.INTaskListResolutionResult
  - ObjC.Intents.INTaskPriorityResolutionResult
  - ObjC.Intents.INTaskResolutionResult
  - ObjC.Intents.INTaskStatusResolutionResult
  - ObjC.Intents.INTemperatureResolutionResult
  - ObjC.Intents.INTemporalEventTrigger
  - ObjC.Intents.INTemporalEventTriggerResolutionResult
  - ObjC.Intents.INTemporalEventTriggerTypeOptionsResolutionResult
  - ObjC.Intents.INTermsAndConditions
  - ObjC.Intents.INTextNoteContent
  - ObjC.Intents.INTicketedEvent
  - ObjC.Intents.INTicketedEventReservation
  - ObjC.Intents.INTimeIntervalResolutionResult
  - ObjC.Intents.INTrainReservation
  - ObjC.Intents.INTrainTrip
  - ObjC.Intents.INTransferMoneyIntent
  - ObjC.Intents.INTransferMoneyIntentResponse
  - ObjC.Intents.INURLResolutionResult
  - ObjC.Intents.INUnsendMessagesIntent
  - ObjC.Intents.INUnsendMessagesIntentResponse
  - ObjC.Intents.INUpcomingMediaManager
  - ObjC.Intents.INUpdateMediaAffinityIntent
  - ObjC.Intents.INUpdateMediaAffinityIntentResponse
  - ObjC.Intents.INUpdateMediaAffinityMediaItemResolutionResult
  - ObjC.Intents.INUserContext
  - ObjC.Intents.INVisualCodeTypeResolutionResult
  - ObjC.Intents.INVocabulary
  - ObjC.Intents.INVoiceShortcut
  - ObjC.Intents.INVoiceShortcutCenter
  - ObjC.Intents.INVolumeResolutionResult
  - ObjC.Intents.INWorkoutGoalUnitTypeResolutionResult
  - ObjC.Intents.INWorkoutLocationTypeResolutionResult
  - ObjC.Intents.Internal.Classes
  - ObjC.Intents.Internal.Enums
  - ObjC.Intents.NSExtensionContext
  - ObjC.Intents.NSString
  - ObjC.Intents.NSUserActivity
  - ObjC.Intents.UNMutableNotificationContent
  - ObjC.Intents.UNNotificationContent
