name:                apple-syncservices-coredata-gen-ext
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the SyncServices extensions on CoreData framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- apple-coredata-gen
- apple-foundation-gen
- apple-syncservices-gen

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.SyncServices.NSPersistentStoreCoordinator
