name:                objc-inputmethodkit
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the InputMethodKit framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-foundation

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.InputMethodKit.IMKCandidates
  - ObjC.InputMethodKit.IMKInputController
  - ObjC.InputMethodKit.IMKServer
  - ObjC.InputMethodKit.Internal.Classes
  - ObjC.InputMethodKit.NSObject
