name:                objc-coredata
version:             0.1.0.0
synopsis:            Generated Haskell bindings for the CoreData framework
license:             BSD-3-Clause

dependencies:
- base >= 4.7 && < 5
- haskell-obj-c
- libffi
- objc-appkit
- objc-cloudkit
- objc-corespotlight
- objc-foundation
- objc-syncservices

ghc-options:
- -Wall
- -Wno-orphans

library:
  source-dirs: src
  exposed-modules:
  - ObjC.CoreData.CKDatabase
  - ObjC.CoreData.Enums
  - ObjC.CoreData.Internal.Classes
  - ObjC.CoreData.Internal.Enums
  - ObjC.CoreData.NSAsynchronousFetchRequest
  - ObjC.CoreData.NSAsynchronousFetchResult
  - ObjC.CoreData.NSAtomicStore
  - ObjC.CoreData.NSAtomicStoreCacheNode
  - ObjC.CoreData.NSBatchDeleteRequest
  - ObjC.CoreData.NSBatchDeleteResult
  - ObjC.CoreData.NSBatchInsertRequest
  - ObjC.CoreData.NSBatchInsertResult
  - ObjC.CoreData.NSBatchUpdateRequest
  - ObjC.CoreData.NSBatchUpdateResult
  - ObjC.CoreData.NSCompositeAttributeDescription
  - ObjC.CoreData.NSConstraintConflict
  - ObjC.CoreData.NSCoreDataCoreSpotlightDelegate
  - ObjC.CoreData.NSCustomMigrationStage
  - ObjC.CoreData.NSDerivedAttributeDescription
  - ObjC.CoreData.NSEntityDescription
  - ObjC.CoreData.NSEntityMapping
  - ObjC.CoreData.NSEntityMigrationPolicy
  - ObjC.CoreData.NSExpressionDescription
  - ObjC.CoreData.NSFetchIndexDescription
  - ObjC.CoreData.NSFetchIndexElementDescription
  - ObjC.CoreData.NSFetchRequest
  - ObjC.CoreData.NSFetchRequestExpression
  - ObjC.CoreData.NSFetchedPropertyDescription
  - ObjC.CoreData.NSFetchedResultsController
  - ObjC.CoreData.NSIncrementalStore
  - ObjC.CoreData.NSIncrementalStoreNode
  - ObjC.CoreData.NSLightweightMigrationStage
  - ObjC.CoreData.NSManagedObject
  - ObjC.CoreData.NSManagedObjectID
  - ObjC.CoreData.NSManagedObjectModel
  - ObjC.CoreData.NSManagedObjectModelReference
  - ObjC.CoreData.NSMappingModel
  - ObjC.CoreData.NSMergeConflict
  - ObjC.CoreData.NSMergePolicy
  - ObjC.CoreData.NSMigrationManager
  - ObjC.CoreData.NSMigrationStage
  - ObjC.CoreData.NSPersistentCloudKitContainer
  - ObjC.CoreData.NSPersistentCloudKitContainerEvent
  - ObjC.CoreData.NSPersistentCloudKitContainerEventRequest
  - ObjC.CoreData.NSPersistentCloudKitContainerEventResult
  - ObjC.CoreData.NSPersistentCloudKitContainerOptions
  - ObjC.CoreData.NSPersistentContainer
  - ObjC.CoreData.NSPersistentHistoryChange
  - ObjC.CoreData.NSPersistentHistoryChangeRequest
  - ObjC.CoreData.NSPersistentHistoryResult
  - ObjC.CoreData.NSPersistentHistoryToken
  - ObjC.CoreData.NSPersistentHistoryTransaction
  - ObjC.CoreData.NSPersistentStore
  - ObjC.CoreData.NSPersistentStoreAsynchronousResult
  - ObjC.CoreData.NSPersistentStoreCoordinator
  - ObjC.CoreData.NSPersistentStoreDescription
  - ObjC.CoreData.NSPersistentStoreRequest
  - ObjC.CoreData.NSPersistentStoreResult
  - ObjC.CoreData.NSPropertyDescription
  - ObjC.CoreData.NSPropertyMapping
  - ObjC.CoreData.NSQueryGenerationToken
  - ObjC.CoreData.NSRelationshipDescription
  - ObjC.CoreData.NSSaveChangesRequest
  - ObjC.CoreData.NSStagedMigrationManager
